const path=require('path');
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const tests=[];const test=(name,fn)=>{try{fn();tests.push({name,status:'PASS'});}catch(e){tests.push({name,status:'FAIL',error:e.message});}};
let currentDay='2026-09-15',lockHeld=false;const counters={reads:0,writes:0}, sheets=new Map(),cache=new Map(),props=new Map([['TEACHER_PASSWORD','test-only-password']]);
function range(sh,row,col,n=1,m=1){return {getValues(){counters.reads++;return Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>sh.data[row+i-1]?.[col+j-1]??''));},getValue(){return this.getValues()[0][0];},setValue(v){return this.setValues([[v]]);},setValues(a){assert.equal(a.length,n);a.forEach(r=>assert.equal(r.length,m));counters.writes++;for(let i=0;i<n;i++){sh.data[row+i-1]??=[];for(let j=0;j<m;j++)sh.data[row+i-1][col+j-1]=a[i][j];}return this;}};}
function sheet(name,data=[]){const sh={data,getLastRow(){return this.data.length;},getLastColumn(){return Math.max(0,...this.data.map(r=>r.length));},getRange(r,c,n,m){if(typeof r==='string'){const z=r.match(/([A-Z]+)(\d+)/);return range(this,Number(z[2]),z[1].charCodeAt(0)-64,1,1);}return range(this,r,c,n,m);},setFrozenRows(){},appendRow(r){this.data.push(r);}};sheets.set(name,sh);return sh;}
sheet('QuestionBank',[['chapter','sentence','target_word','correct','d1','d2','d3'],...JSON.parse(fs.readFileSync(path.join(__dirname,'seed.json'),'utf8'))]);sheet('Schools',[['學校'],['示範學校']]);sheet('Records',[['old'],['preserve me']]);sheet('StudentMistakes',[['legacy'],['preserve me']]);
const spreadsheet={getSheetByName:n=>sheets.get(n)||null,insertSheet:n=>sheet(n)};
const ctx=vm.createContext({console,Date,Set,Map,Number,Object,Array,String,JSON,Math,Error,
  SpreadsheetApp:{getActiveSpreadsheet:()=>spreadsheet,openById:()=>spreadsheet,flush(){}},
  PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k)||null})},
  CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k),removeAll:ks=>ks.forEach(k=>cache.delete(k))})},
  LockService:{getScriptLock:()=>({tryLock(){assert.equal(lockHeld,false);lockHeld=true;return true;},releaseLock(){lockHeld=false;}})},
  Utilities:{getUuid:()=>crypto.randomUUID(),Charset:{UTF_8:'utf8'},DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(algo,s,charset)=>[...crypto.createHash(algo).update(charset==='utf8'?s:s.replace(/[^\x00-\x7F]/g,'?')).digest()],newBlob:s=>({getBytes:()=>Buffer.from(s)}),formatDate:()=>currentDay},
  HtmlService:{createHtmlOutputFromFile(){return {setTitle(){return this;},addMetaTag(){return this;}};}},ScriptApp:{getService:()=>({getUrl:()=> 'https://script.google.com/test/exec'})}
});vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/apps-script/Code.gs'),'utf8'),ctx);
test('First paint does not read Sheets or Drive',()=>{const before=counters.reads;ctx.doGet();assert.equal(counters.reads,before);});
test('Bootstrap validates and caches bank',()=>{const b=ctx.getBootstrap();assert.equal(b.total,10);const n=counters.reads;ctx.getBootstrap();assert.equal(counters.reads,n);});
test('Initializer never clears existing data',()=>{const before=JSON.stringify([...sheets].map(([k,v])=>[k,v.data]));ctx.setupSystem_();assert.equal(sheets.get('Records').data[1][0],'preserve me');assert.equal(sheets.get('QuestionBank').data.length,11);assert.equal(sheets.get('StudentMistakes').data[1][0],'preserve me');});
test('Question identity distinguishes same word in different passages',()=>{const a={chapter:'A',sentence:'甲之乙',targetWord:'之'};assert.notEqual(ctx.questionKey_(a),ctx.questionKey_({...a,chapter:'B'}));assert.notEqual(ctx.questionKey_(a),ctx.questionKey_({...a,sentence:'丙之丁'}));});
test('Student identity does not depend on display name or team',()=>{assert.equal(ctx.identityKey_({studentSchool:'S',studentClass:'2A',studentNumber:'01',studentName:'x'}),ctx.identityKey_({studentSchool:'S',studentClass:'2A',studentNumber:'01',studentName:'y'}));});
test('Invalid and repeated options are omitted without deleting rows',()=>{sheets.get('QuestionBank').data.push(['A','句','字','對','對','錯','錯']);cache.clear();assert.equal(ctx.getBootstrap().total,10);assert.equal(sheets.get('QuestionBank').data.length,12);});
test('HTML stripped from imported question text',()=>{assert(!ctx.bank_()[0].sentence.includes('<span'));});
test('Default teacher password is refused',()=>{props.set('TEACHER_PASSWORD','8888');assert.throws(()=>ctx.teacherLogin('8888'));props.set('TEACHER_PASSWORD','test-only-password');});
let teacher;test('Teacher functions require an authenticated token',()=>{assert.throws(()=>ctx.getTeacherAnalytics('bad',{}));teacher=ctx.teacherLogin('test-only-password').token;assert(ctx.getTeacherAnalytics(teacher,{}).success);});
test('Seeded question order is reproducible',()=>{assert.equal(JSON.stringify(ctx.select_({seed:44,count:5})),JSON.stringify(ctx.select_({seed:44,count:5})));});
test('Invalid chapter and oversized snapshot produce explicit errors',()=>{assert.throws(()=>ctx.select_({chapter:'missing'}));assert.throws(()=>ctx.snapshot_([{sentence:'a'.repeat(46000)}]));});
let run,answer;const profile={studentSchool:'S',studentClass:'2 A',studentNumber:'1',studentName:'=HYPERLINK("x")'};
test('Practice stores immutable questions and normalizes identity',()=>{run=ctx.startPractice(profile,{chapter:'all',count:2,seed:10});assert.equal(run.questions.length,2);const p=JSON.parse(sheets.get('RunsV2').data[1][2]);assert.equal(p.studentClass,'2A');assert.equal(p.studentNumber,'01');});
test('Scores derived from answers; hint cannot earn first-hit credit',()=>{answer=run.questions.map((q,i)=>({id:q.id,attempts:[q.correct],hinted:i===1}));const result=ctx.savePractice(run.runId,answer);assert.equal(result.score,4);assert.equal(result.accuracy,50);assert.equal(sheets.get('RecordsV2').data.length,2);assert(sheets.get('RecordsV2').data[1][5].startsWith("'="));});
test('Repeated save never duplicates score or resets mastery',()=>{const m=sheets.get('MistakesV2').data[1];m[3]=2;m[4]='2026-09-17';ctx.savePractice(run.runId,answer);assert.equal(sheets.get('RecordsV2').data.length,2);assert.equal(m[3],2);});
test('Timeout is a failed first attempt even with a recorded correct option',()=>{const q=run.questions[0],r=ctx.result_(q,{attempts:[q.correct],timedOut:true});assert.equal(r.score,0);assert.equal(r.firstCorrect,false);});
test('Duplicate question IDs cannot substitute for a complete submission',()=>{const r=ctx.startPractice(profile,{count:2,seed:7});assert.throws(()=>ctx.savePractice(r.runId,[{id:r.questions[0].id},{id:r.questions[0].id}]));});
test('Mastery requires three distinct later dates',()=>{const q=run.questions[0];ctx.updateMistakes_('person',[q],[{firstCorrect:false}],'failed');for(let i=0;i<3;i++)ctx.updateMistakes_('person',[q],[{firstCorrect:true}],'same'+i);let m=sheets.get('MistakesV2').data.find(r=>r[0]==='person');assert.equal(m[3],0);for(let i=0;i<3;i++){currentDay='2026-09-'+(16+i);ctx.updateMistakes_('person',[q],[{firstCorrect:true}],'day'+i);}m=sheets.get('MistakesV2').data.find(r=>r[0]==='person');assert.equal(m[3],3);assert.equal(m[5],'RESOLVED');});
test('Classroom reports are idempotent and separate from student grades',()=>{const a={id:'classroom-test-1',className:'2A',teams:[{name:'青龍',score:3}],questions:1};ctx.saveClassroom(teacher,a);ctx.saveClassroom(teacher,a);assert.equal(sheets.get('LessonsV2').data.length,2);});
let room,player;
test('Unique room PINs, host capability and waiting room without players',()=>{room=ctx.createLiveRoom(teacher,{count:2,seed:33});const r2=ctx.createLiveRoom(teacher,{count:1});assert.notEqual(room.pin,r2.pin);assert.equal(ctx.getLiveState(room.pin,room.hostToken).state.status,'WAITING');assert.throws(()=>ctx.hostLiveAction(room.pin,'invalid','start'));});
test('Players join once and cannot impersonate host using their token',()=>{player=ctx.joinLiveRoom(room.pin,profile);assert.throws(()=>ctx.joinLiveRoom(room.pin,profile));assert.throws(()=>ctx.hostLiveAction(room.pin,player.playerToken,'start'));});
test('Unrevealed live question and roster contain neither answer nor tokens',()=>{ctx.hostLiveAction(room.pin,room.hostToken,'start');const r=ctx.getLiveState(room.pin,player.playerToken);assert.equal(r.question.correct,undefined);assert(!JSON.stringify(r).includes(player.playerToken));assert(!JSON.stringify(r).includes(room.hostToken));assert(!JSON.stringify(r).includes('distractors'));});
test('Early answers and invalid phase transitions are rejected',()=>{assert.throws(()=>ctx.submitLiveAnswer(room.pin,player.playerToken,0,'x'));assert.throws(()=>ctx.hostLiveAction(room.pin,room.hostToken,'next'));});
test('Live answer is checked server-side; retry is counted once',()=>{ctx.hostLiveAction(room.pin,room.hostToken,'answer');const q=ctx.room_(room.pin).questions[0];ctx.submitLiveAnswer(room.pin,player.playerToken,0,q.correct);ctx.submitLiveAnswer(room.pin,player.playerToken,0,q.correct);assert.equal(sheets.get('PlayersV2').data[1][4],3);const s=ctx.getLiveState(room.pin,player.playerToken);assert.equal(s.myScore,0);assert.equal(s.players[0].score,0);});
test('Reveal discloses answer and score; next round keeps synchronization',()=>{ctx.hostLiveAction(room.pin,room.hostToken,'reveal');const r=ctx.getLiveState(room.pin,player.playerToken);assert(r.question.correct);assert.equal(r.myScore,3);ctx.hostLiveAction(room.pin,room.hostToken,'next');assert.equal(ctx.getLiveState(room.pin,player.playerToken).state.index,1);});
test('Room expiry is checked and late joins refused',()=>{assert.throws(()=>ctx.joinLiveRoom(room.pin,{...profile,studentNumber:2}));const sh=sheets.get('RoomsV2'),row=sh.data.find(r=>r[0]===room.pin);row[4]='2000-01-01T00:00:00Z';cache.clear();assert.throws(()=>ctx.getLiveState(room.pin,player.playerToken));});
test('Lock released after rejected operation',()=>{assert.equal(lockHeld,false);});
test('Question import refuses unauthenticated callers',()=>{assert.throws(()=>ctx.importQuestions('bad',[]));});
test('Question import validates entire batch before any write',()=>{const before=counters.writes;const token=ctx.teacherLogin('test-only-password').token;assert.throws(()=>ctx.importQuestions(token,[{chapter:'A',sentence:'B',targetWord:'C',correct:'D',distractors:['D','E','F']}]));assert.equal(counters.writes,before);});
test('Question import appends once and skips duplicate retries',()=>{const token=ctx.teacherLogin('test-only-password').token;const q={chapter:'匯入測試',sentence:'甲乙丙',targetWord:'甲',correct:'第一',distractors:['第二','第三','第四']};assert.equal(ctx.importQuestions(token,[q]).added,1);assert.equal(ctx.importQuestions(token,[q]).skipped,1);assert(ctx.bank_().some(x=>x.chapter==='匯入測試'));});
test('Question import refuses spreadsheet formulas',()=>{const token=ctx.teacherLogin('test-only-password').token;assert.throws(()=>ctx.importQuestions(token,[{chapter:'=IMPORTXML("url")',sentence:'B',targetWord:'C',correct:'D',distractors:['E','F','G']} ]));});
const result={passed:tests.filter(t=>t.status==='PASS').length,total:tests.length,tests,counters};fs.writeFileSync(path.join(__dirname,'backend-test-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(result.passed!==tests.length)process.exitCode=1;
module.exports={ctx,sheets,cache,props,sheet};
