const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const {ctx,source,$}=require('./test-client.cjs');
const tests=[];async function test(name,fn){try{await fn();tests.push({name,status:'PASS'});}catch(e){tests.push({name,status:'FAIL',error:e.message});}}
(async()=>{
await test('Internet entry uses HTTPS deployment, never localhost',()=>{const u=new URL(ctx.onlineLink());assert.equal(u.hostname,'script.google.com');assert.equal(u.protocol,'https:');assert(u.pathname.endsWith('/exec'));});
await test('Room invite contains PIN and mode, no host capability',()=>{const u=new URL(ctx.onlineLink({mode:'live',pin:'123456'}));assert.equal(u.searchParams.get('pin'),'123456');assert.equal(u.searchParams.get('mode'),'live');assert.equal([...u.searchParams].length,2);assert(!u.toString().includes('token'));});
await test('QR generation works for the complete long Google deployment URL',()=>{const svg=ctx.qrSvg(ctx.onlineLink({mode:'live',pin:'123456'}));assert(svg.startsWith('<svg'));assert(svg.includes('viewBox'));assert(svg.includes('<path'));});
await test('Offline state is visible and online state hides the notice',()=>{ctx.navigator.onLine=false;ctx.updateNetworkBanner();assert(!$('network-banner').classList.contains('hidden'));ctx.navigator.onLine=true;ctx.updateNetworkBanner();assert($('network-banner').classList.contains('hidden'));});
await test('Deep link opens join screen and keeps valid six-digit PIN',()=>{const old=ctx.liveHome;ctx.liveHome=()=>{};vm.runInContext("launchSearch='mode=live&pin=123456'",ctx);assert.equal(ctx.launchRoute(),true);assert.equal($('room-pin').value,'123456');ctx.liveHome=old;});
await test('Malformed PIN is never copied into join field',()=>{const old=ctx.liveHome;ctx.liveHome=()=>{};$('room-pin').value='';vm.runInContext("launchSearch='mode=live&pin=%3Cscript%3E'",ctx);ctx.launchRoute();assert.equal($('room-pin').value,'');ctx.liveHome=old;});
await test('Apps Script URL API restores only approved launch parameters',async()=>{const cloud=vm.createContext({URLSearchParams,Promise,setTimeout,clearTimeout,DEMO:false,REMOTE:false,launchSearch:'iframe=internal',google:{script:{url:{getLocation:fn=>fn({parameter:{mode:'live',pin:'345678',chapter:'勸學',hostToken:'secret'}})}}}});vm.runInContext(source.match(/function readLaunchParams\(\)[\s\S]*?(?=\nfunction launchRoute)/)[0],cloud);await cloud.readLaunchParams();const p=new URLSearchParams(cloud.launchSearch);assert.equal(p.get('pin'),'345678');assert.equal(p.get('chapter'),'勸學');assert.equal(p.get('hostToken'),null);assert.equal(p.get('iframe'),null);});
await test('Multiplayer polling is staggered for a 35-device class',()=>{assert.equal(ctx.livePollDelay_(false,()=>0),4500);assert.equal(ctx.livePollDelay_(false,()=>0.999),5998);assert.equal(ctx.livePollDelay_(true,()=>0),7000);assert.equal(ctx.livePollDelay_(true,()=>0.999),9997);});
await test('Transient multiplayer requests retry but validation errors do not',async()=>{const originalRpc=ctx.rpc,originalTimer=ctx.setTimeout;try{let calls=0;ctx.rpc=async()=>{calls++;if(calls<3)throw Error('同時連線人數較多，系統正在排隊');return {success:true};};ctx.setTimeout=fn=>{fn();return 1;};assert.equal((await ctx.liveRpc_('joinLiveRoom',[],4)).success,true);assert.equal(calls,3);calls=0;ctx.rpc=async()=>{calls++;throw Error('請輸入六位房間碼');};await assert.rejects(()=>ctx.liveRpc_('joinLiveRoom',[],4));assert.equal(calls,1);}finally{ctx.rpc=originalRpc;ctx.setTimeout=originalTimer;}});
await test('Sixteen shared WebP assets are available in Pages build',()=>{const dir=path.resolve(__dirname,'../dist/pages/assets');const files=fs.readdirSync(dir).filter(x=>x.endsWith('.webp'));assert.equal(files.length,16);for(const f of files)assert(fs.statSync(path.join(dir,f)).size>10000);});
const report={passed:tests.filter(t=>t.status==='PASS').length,total:tests.length,tests};fs.writeFileSync(path.join(__dirname,'online-test-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
})();
