const {ctx,sheets,cache}=require('./test-backend.cjs'),assert=require('node:assert/strict'),vm=require('node:vm');
const token=ctx.teacherLogin('test-only-password').token;
const room=ctx.createLiveRoom(token,{mode:'race',count:3,durationSec:600});
const profile={studentSchool:'S',studentClass:'QA',studentNumber:'81'};
const a=ctx.joinLiveRoom(room.pin,profile).playerToken,b=ctx.joinLiveRoom(room.pin,{...profile,studentNumber:'82'}).playerToken;
const state=t=>ctx.getLiveState(room.pin,t);
assert.equal(state(a).question,null);assert.throws(()=>ctx.useRaceStratagem(room.pin,a,0,'hint'));
ctx.hostLiveAction(room.pin,room.hostToken,'start');assert.throws(()=>ctx.hostLiveAction(room.pin,room.hostToken,'next'));
const qs=ctx.room_(room.pin).questions;
assert(state(a).question);assert.equal(state(a).question.correct,undefined);assert.equal(state(a).question.hint,undefined);
assert.throws(()=>ctx.useRaceStratagem(room.pin,'fake',0,'hint'));
assert.throws(()=>ctx.useRaceStratagem(room.pin,room.hostToken,0,'hint'));
ctx.useRaceStratagem(room.pin,a,0,'hint');ctx.useRaceStratagem(room.pin,a,0,'clue');ctx.useRaceStratagem(room.pin,a,0,'rally');
assert.equal(Object.keys(state(a).tools).length,3);assert.equal(Object.keys(state(b).tools).length,0);
assert.equal(ctx.useRaceStratagem(room.pin,a,0,'hint').success,true);
assert.equal(ctx.submitLiveAnswer(room.pin,a,0,qs[0].distractors[0]).retry,true);
assert.equal(state(a).myProgress,0);assert(state(a).retryPending);assert.equal(state(a).lastResult,null);
ctx.submitLiveAnswer(room.pin,a,0,qs[0].correct);assert.equal(state(a).myScore,1);assert.equal(state(a).myProgress,1);assert.equal(state(b).myProgress,0);
ctx.submitLiveAnswer(room.pin,a,0,qs[0].correct);assert.equal(state(a).myScore,1);
assert.throws(()=>ctx.useRaceStratagem(room.pin,a,1,'rally'));assert.throws(()=>ctx.submitLiveAnswer(room.pin,a,2,qs[2].correct));
for(let i=1;i<qs.length;i++)ctx.submitLiveAnswer(room.pin,a,i,qs[i].correct);
assert(state(a).finished);assert.equal(state(a).state.status,'PLAYING');assert.equal(state(a).question,null);
for(let i=0;i<qs.length;i++)ctx.submitLiveAnswer(room.pin,b,i,qs[i].correct);
assert.equal(state(a).state.status,'FINISHED');assert.equal(state(b).lastResult.streak,3);assert.equal(state(b).myScore,9);assert.equal(state(a).myScore,7);
assert.equal(state(room.hostToken).question,null);assert(!JSON.stringify(state(a).players).includes('raceTools'));
const expired=ctx.createLiveRoom(token,{mode:'race',count:1,durationSec:120});const ep=ctx.joinLiveRoom(expired.pin,{...profile,studentNumber:'83'}).playerToken;ctx.hostLiveAction(expired.pin,expired.hostToken,'start');const row=sheets.get('RoomsV2').data.find(r=>r[0]===expired.pin);const st=JSON.parse(row[2]);st.endsAt=Date.now()-1;row[2]=JSON.stringify(st);cache.clear();assert.equal(ctx.getLiveState(expired.pin,ep).state.status,'FINISHED');assert.throws(()=>ctx.submitLiveAnswer(expired.pin,ep,0,'anything'));assert.throws(()=>ctx.useRaceStratagem(expired.pin,ep,0,'hint'));
console.log('PASS Independent race, three server-enforced stratagems, retry scoring, privacy, finish and deadline');
const client=require('./test-client.cjs');vm.runInContext("live={pin:'123456',token:'test',isHost:false};",client.ctx);
const playing={...state(b),state:{...state(b).state,status:'PLAYING',phase:'answer',index:0},question:ctx.publicQ_(qs[0],room.pin),finished:false,lastResult:null,tools:{},retryPending:false};
client.ctx.renderLive(playing);assert(client.$('live-view').innerHTML.includes('孔明點撥'));assert(client.$('live-view').innerHTML.includes('data-live-choice'));assert(!client.$('live-view').innerHTML.includes('PHASES'));
console.log('PASS Waiting-to-playing renders question and all three stratagems without PHASES dependency');
