'use strict';
const $=id=>document.getElementById(id), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const REMOTE=!!location.pathname?.endsWith('/play.html');
const DEMO=!REMOTE&&!(window.google&&google.script&&google.script.run);
const privateStore=DEMO?localStorage:sessionStorage;
const storage={get(k,d=null){try{return JSON.parse(privateStore.getItem('rtk2:'+k))??d;}catch(e){return d;}},set(k,v){try{privateStore.setItem('rtk2:'+k,JSON.stringify(v));return true;}catch(e){return false;}},remove(k){try{privateStore.removeItem('rtk2:'+k);}catch(e){}}};
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
let pollEpoch=0;let boot=null,teacherToken='',game=null,live=null,poll=null,pollBusy=false,timerHandle=null,remaining=30,timerDeadline=0,soundOn=false,audioCtx=null,modalPrevious=null,toastTimer=null,busy=false;
const TEAMS=['青龍軍','白虎軍','朱雀軍','玄武軍'];
const PHASES=['獨立思考','同袍商議','亮出答案','揭曉與修訂'];
const COACH=['先給學生 30 秒，圈出一個字或作一個判斷。巡視後，才進入小組討論。','每人先讀出自己的答案，再比較證據。邀請一位同學準備解釋。','請各組同時亮出白板或答題卡。先請學生說理由，再揭曉答案。','每人用另一種顏色補上一處證據或理由。依判斷、證據和解釋分別給分。'];
function shuffle(a,seed){a=a.slice();let x=Number(seed)||1;const rnd=()=>{let t=x+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function chooseDemo(o){let q=DEMO_QUESTIONS.filter(q=>!o.chapter||o.chapter==='all'||q.chapter===o.chapter);if(!q.length)throw Error('此篇章暫無題目。');return shuffle(q,o.seed||Date.now()).slice(0,Math.max(1,Math.min(30,Number(o.count)||10)));}
function rpc(name,...args){return new Promise((resolve,reject)=>{
  if(DEMO){try{let r;
    if(name==='getBootstrap'){const counts={};DEMO_QUESTIONS.forEach(q=>counts[q.chapter]=(counts[q.chapter]||0)+1);r={success:true,chapters:Object.entries(counts).map(([name,count])=>({name,count})),total:DEMO_QUESTIONS.length,schools:['示範學校'],url:location.href.split('?')[0]};}
    else if(name==='getClassroomQuestions')r={success:true,questions:chooseDemo(args[1])};
    else if(name==='startPractice')r={success:true,runId:uid(),questions:chooseDemo(args[1])};
    else if(name==='savePractice'||name==='saveClassroom')r={success:true,local:true};
    else if(name==='refreshQuestionCache'){resolve(rpc('getBootstrap'));return;}
    else if(name==='getTeacherAnalytics'){const rec=storage.get('records',[]);r={success:true,totalBattles:rec.filter(x=>x.type!=='classroom').length,avgAccuracy:rec.filter(x=>x.type!=='classroom').length?Math.round(rec.filter(x=>x.type!=='classroom').reduce((n,x)=>n+(x.accuracy||0),0)/rec.filter(x=>x.type!=='classroom').length):0,legacyRecords:0,classroomSessions:rec.filter(x=>x.type==='classroom').length,liveRooms:0,difficultWords:[],recent:rec.filter(x=>x.type!=='classroom').slice(-20).reverse().map(x=>({date:x.date,className:x.profile?.studentClass||'課堂',number:x.profile?.studentNumber||'',score:x.score||0,maxScore:x.maxScore||0,accuracy:x.accuracy||0}))};}
    else throw Error('此功能須在已部署的 Google Apps Script 網址使用；本機預覽不會建立真正線上房間。');
    resolve(r);
  }catch(e){reject(e);}return;}
  if(REMOTE){remoteTransport.call(name,args).then(resolve,reject);return;}
  let settled=false;const timeout=setTimeout(()=>{if(!settled){settled=true;reject(Error('連線較慢，請重試。已提交的戰報會按同一編號核對，避免重複記分。'));}},30000);
  google.script.run.withSuccessHandler(r=>{if(settled)return;settled=true;clearTimeout(timeout);if(r&&r.success===false)reject(Error(r.error||'操作未完成。'));else resolve(r);}).withFailureHandler(e=>{if(settled)return;settled=true;clearTimeout(timeout);reject(Error(e.message||String(e)));})[name](...args);
});}
function toast(s){clearTimeout(toastTimer);$('toast').textContent=s;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),5000);}
function sound(ok=true){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=ok?523:220;g.gain.setValueAtTime(.04,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.2);o.start();o.stop(audioCtx.currentTime+.2);}catch(e){}}
function showView(name){if(name!=='battle'){$('projection').textContent='投影模式';}$$('.view').forEach(el=>el.classList.toggle('hidden',el.id!==name+'-view'));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name||(name==='battle'&&b.dataset.nav===(game?.type==='classroom'?'classroom':'practice'))));if(name!=='battle')document.body.classList.remove('projection');window.scrollTo(0,0);}
function showModal(title,body,onSubmit,label='確定'){
  modalPrevious=document.activeElement;$('modal').innerHTML=`<form class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">${esc(title)}</h2>${body}<p id="modal-error" class="error-text" style="margin-top:12px"></p><div class="actions"><button type="button" class="btn ghost" id="modal-cancel">取消</button><button type="submit" class="btn primary" id="modal-submit">${esc(label)}</button></div></form>`;
  $('modal').classList.remove('hidden');$('modal-cancel').onclick=closeModal;
  $('modal').querySelector('form').onsubmit=async e=>{e.preventDefault();$('modal-submit').disabled=true;try{await onSubmit(new FormData(e.target));}catch(err){if($('modal-error'))$('modal-error').textContent=err.message;else toast(err.message);}finally{if($('modal-submit'))$('modal-submit').disabled=false;}};
  $('modal').querySelector('input,select,textarea,button').focus();
}
function closeModal(){$('modal').classList.add('hidden');$('modal').innerHTML='';modalPrevious?.focus();}
function confirmAction(title,text,fn){showModal(title,`<p>${esc(text)}</p>`,async()=>{closeModal();await fn();},'確認');}
async function ensureTeacher(){if(teacherToken)return true;if(DEMO){teacherToken='demo';return true;}return new Promise(resolve=>{
  showModal('軍師驗印','<p>教師主持、軍情報告及開設線上房間需要驗證。</p><label for="teacher-pass">教師密碼</label><input id="teacher-pass" name="password" type="password" autocomplete="current-password" required>',async f=>{const r=await rpc('teacherLogin',f.get('password'));teacherToken=r.token;closeModal();resolve(true);},'驗印入營');
  $('modal-cancel').onclick=()=>{closeModal();resolve(false);};
});}
function profileDialog(callback){const p=storage.get('profile',{});showModal('將領入冊',`<p>建議使用代號。錯題保存在此瀏覽器；共用電腦請使用自己的班別和學號。</p><label for="student-school">學校</label><select id="student-school" name="studentSchool">${(boot?.schools||['示範學校']).map(s=>`<option ${p.studentSchool===s?'selected':''}>${esc(s)}</option>`).join('')}</select><div class="two"><div><label for="student-class">班別</label><input id="student-class" name="studentClass" value="${esc(p.studentClass||'2A')}" maxlength="12" required></div><div><label for="student-num">學號</label><input id="student-num" name="studentNumber" value="${esc(p.studentNumber||'')}" inputmode="numeric" pattern="[0-9]{1,3}" maxlength="3" required></div></div><label for="student-name">將領代號（選填）</label><input id="student-name" name="studentName" value="${esc(p.studentName||'')}" maxlength="30"><p style="margin-top:17px">選擇你的軍團</p><div class="commander-grid" role="group" aria-label="選擇軍團">${TEAMS.map((t,i)=>`<label class="commander-choice"><input type="radio" name="studentTeam" value="${t}" ${(p.studentTeam||TEAMS[0])===t?'checked':''}><span class="commander-art" style="--commander:var(--asset${i})" aria-hidden="true"></span><span>${t}<small>${COMMANDERS[i]}</small></span></label>`).join('')}</div>`,async f=>{const p=Object.fromEntries(f);p.studentClass=p.studentClass.replace(/\s/g,'').toUpperCase();p.studentNumber=String(Number(p.studentNumber)).padStart(2,'0');storage.set('profile',p);closeModal();await callback(p);},'整備出發');}
function options(){return {chapter:$('chapter').value,count:Number($('count').value),seed:Number(new URLSearchParams(launchSearch).get('seed'))||Date.now(),mode:'practice'};}
function selectedChapter(){return $('chapter').value==='all'?'全篇混合':$('chapter').value;}
async function bootApp(){
  try{const initial=await Promise.all([rpc('getBootstrap'),readLaunchParams()]);boot=initial[0];renderCamp();$('connection').innerHTML=`<span class="dot"></span>${DEMO?'本機示範':'軍情已接通'}`;$('footer-status').textContent=`${DEMO?'示範題庫 · 不連接原有試算表':'校本題庫 · Google Sheets'} · ${boot.total} 題`;
    if(DEMO){$('boot-notice').textContent='本機預覽｜使用原檔內附的 10 題示例；課堂攻城及個人研習可操作，雲端成績及線上房間須部署後使用。';$('boot-notice').classList.remove('hidden');}
    else if(!boot.total){$('boot-notice').textContent='題庫目前沒有有效題目。請檢查 QuestionBank 的七個基本欄位；系統不會覆蓋原有資料。';$('boot-notice').classList.remove('hidden');}
    const unsynced=storage.get('pending');if(unsynced&&!storage.get('active')){const b=document.createElement('button');b.className='btn small';b.textContent='接續同步上次戰報';b.onclick=()=>{game=unsynced;renderResult();syncResult();};$('boot-notice').appendChild(b);$('boot-notice').classList.remove('hidden');}const routed=launchRoute();const pending=storage.get('active');if(!routed&&pending?.questions?.length){showModal('接續未完的征途','<p>找到此瀏覽器尚未完成的進度。可以接續，或取消後開新局。</p>',()=>{game=pending;closeModal();showView('battle');renderQuestion();},'接續征途');}
  }catch(e){$('connection').textContent='題庫未接通';$('boot-notice').innerHTML=`${esc(e.message)} <button class="btn small" id="retry-boot">重試連線</button>`;$('boot-notice').classList.remove('hidden');$('retry-boot').onclick=bootApp;}
}
function renderCamp(){const old=$('chapter').value;const requested=new URLSearchParams(launchSearch).get('chapter');$('chapter').innerHTML='<option value="all">全部篇章 · 混合挑戰</option>'+boot.chapters.map(c=>`<option value="${esc(c.name)}">${esc(c.name)} · ${c.count} 題</option>`).join('');$('chapter').value=boot.chapters.some(c=>c.name===(requested||old))?(requested||old):'all';
  const countParam=Number(new URLSearchParams(launchSearch).get('count'));if(countParam>=1&&countParam<=30){if(!Array.from($('count').options).some(o=>Number(o.value)===countParam))$('count').add(new Option(countParam+' 關 · 同題挑戰',countParam));$('count').value=countParam;}
  $('bank-total').textContent=boot.total+' 題';$('start-classroom').disabled=$('start-practice').disabled=!boot.total;
  const spots=[[16,77],[34,63],[51,53],[66,37],[84,27],[65,77]],names=['成都','漢中','祁山','天水','長安','荊州'];
  $('cities').innerHTML=boot.chapters.slice(0,6).map((c,i)=>`<button class="city" style="left:${spots[i][0]}%;top:${spots[i][1]}%" data-chapter="${esc(c.name)}" aria-label="${names[i]}：研習${esc(c.name)}"><svg class="fort-svg" viewBox="0 0 80 62" aria-hidden="true"><ellipse cx="40" cy="52" rx="33" ry="8" fill="#0b201a66"/><path d="M10 32 39 21 70 34 41 47Z" fill="#897c5d" stroke="#d4c18f"/><path d="M10 32 10 47 41 60 41 47Z" fill="#a19370" stroke="#d5c390"/><path d="M41 47 70 34 70 48 41 60Z" fill="#625e4d" stroke="#b5a580"/><path d="M18 33 18 23 40 15 59 23 59 36 40 43Z" fill="#6e6952" stroke="#dfcca1"/><path d="M14 24 40 10 65 24 42 31Z" fill="#344637" stroke="#b29b61"/><path d="M24 16 40 6 57 16 40 23Z" fill="#3b4c3d" stroke="#dbc184"/><path d="M31 32 31 41 40 45 40 36Z" fill="#2a3127"/><path d="M10 32 10 28 16 26 16 30 M21 29 21 25 26 23 26 27 M54 41 54 37 60 35 60 39 M65 37 65 33 70 31 70 35" stroke="#dfc897" stroke-width="3" fill="none"/></svg><span class="city-flag">${i<3?'蜀':'魏'}</span><span class="city-name">${names[i]}</span><small>${esc(c.name)}</small></button>`).join('');$$('.city').forEach(b=>b.onclick=()=>{$('chapter').value=b.dataset.chapter;updateMission();});updateMission();}
function updateMission(){$('mission-title').textContent=selectedChapter();$$('.city').forEach(b=>b.classList.toggle('selected',b.dataset.chapter===$('chapter').value));}
async function startClassroom(){if(!boot?.total)return;if(!await ensureTeacher())return;showModal('頒布課堂軍令','<p>同學使用紙筆及白板。評分由老師按判斷、證據、解釋各給一分。</p><label for="lesson-class">班別</label><input id="lesson-class" name="className" value="2A" maxlength="20" required><label for="team-count">軍團數目</label><select id="team-count" name="teams"><option>4</option><option>5</option><option>6</option></select>',async f=>{const opts=options();const r=await rpc('getClassroomQuestions',teacherToken,opts);const n=Number(f.get('teams'));game=newGame('classroom',r.questions);game.className=String(f.get('className'));game.school=boot.schools[0]||'';game.teams=Array.from({length:n},(_,i)=>({name:TEAMS[i]||['麒麟軍','鳳凰軍'][i-4],score:0}));game.history=[];closeModal();begin();},'開始課堂攻城');}
function newGame(type,questions,profile={}){return {id:uid(),type,questions,index:0,phase:0,answers:[],attempts:[],hinted:false,timedOut:false,done:false,score:0,profile,seed:options().seed,chapter:$('chapter').value,date:new Date().toISOString(),awards:{}};}
async function startPractice(){if(!boot?.total)return;profileDialog(async p=>{try{setBusy(true);const opts=options();const r=await rpc('startPractice',p,opts);game=newGame('practice',r.questions,p);game.runId=r.runId;game.seed=opts.seed;begin();}catch(e){toast(e.message);}finally{setBusy(false);}});}
function setBusy(b){busy=b;$('start-classroom').disabled=$('start-practice').disabled=b||!boot?.total;}
function persist(){if(game&&!storage.set('active',game))toast('瀏覽器儲存空間不足，請在離開前匯出戰報。');}
function begin(){if(!game.questions.length){toast('沒有可用題目。');return;}stopTimer();persist();showView('battle');renderQuestion();}
function sentenceHTML(q){const t=String(q.sentence),needle=String(q.targetWord);const i=t.indexOf(needle);return i<0?esc(t):esc(t.slice(0,i))+'<mark>'+esc(needle)+'</mark>'+esc(t.slice(i+needle.length));}
function renderQuestion(){$('options').classList.remove('hidden');stopTimer();remaining=game.type==='classroom'?30:60;updateTimer();const q=game.questions[game.index],classroom=game.type==='classroom';document.body.classList.toggle('practice-mode',!classroom);document.body.classList.toggle('review-mode',game.type==='vault');
  $('battle-type').textContent=classroom?'課堂攻城 · 教師主持':game.type==='vault'?'溫故知新 · 個人重溫':'單騎千里 · 獨立研習';$('battle-title').textContent=q.chapter;$('battle-subtitle').textContent=classroom?'每人先留下答案，再與同伴商議。':'仔細閱讀句子，按語境判斷字詞意思。';$('question-count').textContent=`第 ${game.index+1} 關 / 共 ${game.questions.length} 關`;$('progress').style.width=(game.index/game.questions.length*100)+'%';$('q-chapter').textContent='《'+q.chapter+'》';$('sentence').innerHTML=sentenceHTML(q);$('question-prompt').textContent=`句中「${q.targetWord}」的意思是甚麼？`;
  $('print-before').classList.toggle('hidden',!classroom);$('teams-card').classList.toggle('hidden',!classroom);$('practice-card').classList.toggle('hidden',classroom);$('phases').classList.toggle('hidden',!classroom);$('skip').classList.toggle('hidden',classroom||game.done);$('personal-score').textContent=game.score;
  $('hint-box').classList.add('hidden');$('feedback').classList.add('hidden');$('hint').disabled=game.done;$('advance').classList.toggle('hidden',!classroom&&!game.done);
  const choices=shuffle([q.correct,...q.distractors],game.seed+game.index);$('options').innerHTML=choices.map((v,i)=>`<button class="option ${game.attempts.includes(v)?(v===q.correct?'correct':'wrong'):''}" data-choice="${esc(v)}"><span class="letter">${'ABCD'[i]}</span><span>${esc(v)}</span></button>`).join('');
  $$('.option').forEach(b=>{b.disabled=classroom||game.done||game.attempts.includes(b.dataset.choice);b.onclick=()=>answer(b.dataset.choice);});
  if(classroom){renderPhase();renderTeams();}else{$('q-label').textContent='語境判讀';$('coach-title').textContent='看清楚，再判斷';$('coach').textContent='先找字詞前後的線索。需要協助時可使用錦囊；提示後答對也能獲得軍功。';if(game.done)revealPractice();}
  if(game.hinted&&!game.done)showHint(false);
}
function renderPhase(){const phase=game.phase;$('phases').innerHTML=PHASES.map((s,i)=>`<div class="phase ${i===phase?'current':''}">${i+1}　${s}</div>`).join('');$('q-label').textContent=PHASES[phase];$('coach-title').textContent=PHASES[phase];$('coach').textContent=COACH[phase];$('options').classList.toggle('hidden',phase===0);$('advance').textContent=phase===3?(game.index===game.questions.length-1?'完成戰役 →':'下一關 →'):['進入商議 →','準備亮板 →','揭曉與修訂 →'][phase];
  if(phase===3){const q=game.questions[game.index];$$('.option').forEach(b=>b.classList.toggle('correct',b.dataset.choice===q.correct));$('feedback').textContent=`參考釋義：${q.correct}。${q.explanation||'請回到句中，說明這個解釋為何符合語境；並在自己的答案補上一處理由。'}`;$('feedback').classList.remove('hidden');} }
function renderTeams(){const key=game.index;const checks=game.awards[key]||{};$('teams').innerHTML=game.teams.map((t,i)=>`<div class="team"><div class="team-name"><span class="team-identity"><i class="team-avatar" style="--commander:var(--asset${i%4})" aria-hidden="true"></i>${esc(t.name)}</span><strong>${t.score}</strong></div><div class="team-controls">${['判斷','證據','解釋'].map((s,j)=>`<button class="btn ghost" data-team="${i}" data-criterion="${j}" ${checks[i+':'+j]||game.phase!==3?'disabled':''}>${s} ＋1</button>`).join('')}</div><div class="bar"><i style="width:${Math.min(100,t.score/(game.questions.length*3)*100)}%"></i></div></div>`).join('');$$('[data-team]').forEach(b=>b.onclick=()=>award(Number(b.dataset.team),Number(b.dataset.criterion)));$('undo-score').disabled=!game.history.length;}
function award(i,j){const key=i+':'+j;game.awards[game.index]=game.awards[game.index]||{};if(game.awards[game.index][key]||game.phase!==3)return;game.awards[game.index][key]=true;game.teams[i].score++;battleFlash("穩步推進");game.history.push({index:game.index,team:i,key});persist();renderTeams();sound();}
function undoScore(){const a=game.history.pop();if(!a)return;delete game.awards[a.index][a.key];game.teams[a.team].score=Math.max(0,game.teams[a.team].score-1);persist();renderTeams();}
function advance(){if(!game||game.completed)return;if(game.type==='classroom'&&game.phase<3){game.phase++;stopTimer();persist();renderPhase();renderTeams();return;}if(game.type!=='classroom'&&!game.done)return;
  if(game.index+1>=game.questions.length){finish();return;}game.index++;game.phase=0;game.attempts=[];game.hinted=false;game.timedOut=false;game.done=false;$('options').classList.remove('hidden');persist();renderQuestion();}
function answer(choice){if(!game||game.type==='classroom'||game.done||game.attempts.includes(choice))return;const q=game.questions[game.index];game.attempts.push(choice);
  if(choice===q.correct){stopTimer();game.done=true;const first=game.attempts.length===1&&!game.hinted&&!game.timedOut;game.score+=first?3:1;game.answers.push({id:q.id,attempts:game.attempts.slice(),hinted:game.hinted,timedOut:false,firstCorrect:first,score:first?3:1});sound();battleFlash(first?"一語中的":"溫故知新");revealPractice();}
  else{sound(false);$('feedback').textContent='先別急着選下一項。再看字詞前後，哪個意思能令整句讀得通順？';$('feedback').className='feedback error';const b=$$('.option').find(b=>b.dataset.choice===choice);b.classList.add('wrong');b.disabled=true;}
  persist();}
function revealPractice(){const q=game.questions[game.index];$('options').classList.remove('hidden');$$('.option').forEach(b=>{b.disabled=true;b.classList.toggle('correct',b.dataset.choice===q.correct);});$('feedback').className='feedback';$('feedback').textContent=`參考釋義：${q.correct}。${q.explanation||'把這個意思代回原句，再讀一次，檢查語意是否通順。'}`;$('advance').textContent=game.index===game.questions.length-1?'完成戰役 →':'下一關 →';$('advance').classList.remove('hidden');$('skip').classList.add('hidden');$('hint').disabled=true;$('personal-score').textContent=game.score;}
function skipQuestion(timeout=false){if(!game||game.done||game.type==='classroom')return;stopTimer();game.done=true;game.timedOut=timeout;game.answers.push({id:game.questions[game.index].id,attempts:game.attempts.slice(),hinted:game.hinted,timedOut:timeout,firstCorrect:false,score:0});persist();revealPractice();}
function showHint(set=true){if(!game||game.done)return;if(set){game.hinted=true;persist();}const q=game.questions[game.index];$('hint-box').textContent=q.hint||`先讀「${q.targetWord}」前後的文字，辨認誰在做甚麼；把各選項代回原句，看看哪個意思最通順。`;$('hint-box').classList.remove('hidden');}
function stopTimer(){if(timerHandle){remaining=Math.max(0,Math.ceil((timerDeadline-Date.now())/1000));clearInterval(timerHandle);timerHandle=null;}$('timer-toggle').textContent='開始計時';}
function updateTimer(){$('timer').textContent=remaining+' 秒';}
function toggleTimer(){if(!game||game.done)return;if(timerHandle){stopTimer();updateTimer();return;}if(remaining<=0)remaining=game.type==='classroom'?30:60;timerDeadline=Date.now()+remaining*1000;$('timer-toggle').textContent='暫停';timerHandle=setInterval(()=>{remaining=Math.max(0,Math.ceil((timerDeadline-Date.now())/1000));updateTimer();if(remaining===0){stopTimer();sound(false);if(game.type==='classroom')toast('思考時間到。由老師決定何時進入下一階段。');else skipQuestion(true);}},250);}
function addTime(){remaining+=15;if(timerHandle)timerDeadline+=15000;updateTimer();}
function profileKey(p){return [p.studentSchool,p.studentClass,p.studentNumber].join('|');}
function updateVault(){if(game.type==='classroom')return;const key=profileKey(game.profile),all=storage.get('vault',{}),items=all[key]||[];const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  game.questions.forEach((q,i)=>{const a=game.answers[i];if(!a)return;let m=items.find(x=>x.id===q.id);if(!a.firstCorrect){if(!m){m={...q,level:0,last:today,status:'ACTIVE'};items.push(m);}m.level=0;m.last=today;m.status='ACTIVE';}else if(m&&m.status==='ACTIVE'&&m.last!==today){m.level++;m.last=today;if(m.level>=3)m.status='RESOLVED';}});all[key]=items;storage.set('vault',all);}
async function finish(){stopTimer();if(!game||game.completed)return;game.completed=true;storage.remove('active');const records=storage.get('records',[]);if(!records.some(x=>x.id===game.id)){updateVault();game.accuracy=game.type==='classroom'?0:Math.round(game.answers.filter(a=>a.firstCorrect).length/game.questions.length*100);records.push({id:game.id,type:game.type,date:new Date().toISOString(),profile:game.profile,score:game.score,maxScore:game.questions.length*3,accuracy:game.accuracy});storage.set('records',records.slice(-200));}renderResult();await syncResult();}
function renderResult(){showView('result');const classroom=game.type==='classroom',wrong=game.questions.filter((q,i)=>!game.answers[i]?.firstCorrect);$('result-view').innerHTML=`<div class="victory-banner"><div class="eyebrow">捷報入營 · AFTER ACTION REPORT</div><h2>${classroom?'諸將同心，學有所進。':'每一次訂正，都是進步。'}</h2><p>${game.questions.length} 關研習已完成。帶着這次的發現，走向下一篇文章。</p><div class="victory-stamp">${classroom?'同心':'精進'}</div></div>${classroom?`<div class="stats-grid class-stats">${game.teams.map(t=>`<div class="stat">${esc(t.name)}<b>${t.score}</b><span class="muted">軍功 · 判斷／證據／解釋</span></div>`).join('')}</div>`:`<div class="stats-grid"><div class="stat">本次軍功<b>${game.score}</b><span class="muted">滿分 ${game.questions.length*3}</span></div><div class="stat">獨立首答正確<b>${game.accuracy}%</b><span class="muted">使用提示後不計入首答</span></div><div class="stat">值得重溫<b>${wrong.length}</b><span class="muted">不同日子再試一次</span></div></div>`}<div class="notice" id="sync-status">正在整理戰報…</div><div class="toolbar"><button class="btn primary" id="result-home">返回軍機處</button><button class="btn" id="export-report">匯出戰報</button>${classroom?'<button class="btn" id="print-paper">列印答題紙</button>':'<button class="btn" id="result-vault">查看錯題</button><button class="btn" id="share-seed">複製同題挑戰連結</button>'}<button class="btn hidden" id="retry-sync">重試同步</button></div>${!classroom&&wrong.length?'<div class="rule"></div><h3 class="gold">本次重溫札記</h3>'+wrong.map(q=>`<article class="mistake"><span class="eyebrow">${esc(q.chapter)}</span><p>${esc(q.sentence)}</p><span class="gold">「${esc(q.targetWord)}」：${esc(q.correct)}</span></article>`).join(''):''}`;
  $('result-home').onclick=()=>{game=null;showView('camp');};$('export-report').onclick=exportReport;$('retry-sync').onclick=syncResult;if(classroom)$('print-paper').onclick=printPaper;else{$('result-vault').onclick=openVault;$('share-seed').onclick=shareSeed;}}
async function syncResult(){const current=game;if(!current||!$('sync-status'))return;if(current.type==='vault'){$('sync-status').textContent='重溫已保存在此瀏覽器的個人錯題紀錄。';return;}try{$('retry-sync').disabled=true;let r;if(current.type==='classroom'){if(!await ensureTeacher())throw Error('尚未登入教師帳戶。');r=await rpc('saveClassroom',teacherToken,{id:current.id,school:current.school,className:current.className,chapter:current.chapter,questions:current.questions.length,teams:current.teams});}else r=await rpc('savePractice',current.runId,current.answers);if(game!==current||!$('sync-status'))return;$('sync-status').textContent=r.local?'本機示範：戰報已保存在此瀏覽器，沒有寫入 Google Sheets。':'戰報已成功寫入 Google Sheets。';$('retry-sync').classList.add('hidden');storage.remove('pending');}catch(e){storage.set('pending',current);if($('sync-status')){$('sync-status').textContent='尚未同步：'+e.message;$('retry-sync').classList.remove('hidden');}}finally{if($('retry-sync'))$('retry-sync').disabled=false;}}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportReport(){const report={version:'2.0',type:game.type,date:game.date,className:game.className||game.profile.studentClass,number:game.profile.studentNumber,teams:game.teams,score:game.score,accuracy:game.accuracy,questions:game.questions.map((q,i)=>({chapter:q.chapter,sentence:q.sentence,targetWord:q.targetWord,...game.answers[i]}))};download('出師北伐-戰報.json',JSON.stringify(report,null,2));}
function printPaper(){$('print-sheet').innerHTML=`<header><h1>出師北伐 · 課堂答題紙</h1><p>班別：________　姓名／學號：________　日期：________</p><p>先獨立判斷，再找證據，討論後用另一種顏色修訂。</p></header>`+game.questions.map((q,i)=>`<article><b>第 ${i+1} 關 · ${esc(q.chapter)}</b><p>${esc(q.sentence)}</p><p>「${esc(q.targetWord)}」的意思：________________________</p><p>我的證據與理由：</p><div class="writing-line"></div><p>討論後，我補充／修改：</p><div class="writing-line"></div></article>`).join('');window.print();}
async function shareSeed(){const base=DEMO?location.href.split('?')[0]:onlineLink(),url=new URL(base);url.searchParams.set('seed',game.seed);url.searchParams.set('chapter',game.chapter);url.searchParams.set('count',game.questions.length);try{await navigator.clipboard.writeText(url.toString());toast('已複製挑戰連結；使用同一版本題庫時題組相同。連結不包含學生姓名。');}catch(e){showModal('同題挑戰',`<p>題庫更新可能改變題組。請複製以下連結：</p><label for="share-url">挑戰網址</label><input id="share-url" readonly value="${esc(url)}">`,()=>closeModal(),'完成');}}
function openVault(){stopTimer();const p=storage.get('profile');if(!p){profileDialog(()=>openVault());return;}const items=(storage.get('vault',{})[profileKey(p)]||[]).filter(x=>x.status==='ACTIVE');showView('vault');$('vault-view').innerHTML=`<div class="page-head scene-head scene-vault"><div><div class="eyebrow">溫故而知新 · REVIEW</div><h2>重整行囊，再進一步。</h2><p>${esc(p.studentClass)} · ${esc(p.studentNumber)} 號｜在三個不同日子獨立答對，完成重溫。</p></div><button class="btn ghost" id="switch-profile">切換將領</button></div><div class="notice">錯題保存在這部裝置的瀏覽器，不會自動跨裝置同步。當日反覆練習不提升重溫等級。</div>${items.length?`<button class="btn primary" id="review-start">開始重溫 · ${Math.min(30,items.length)} 題</button>`:'<div class="empty">尚無待重溫題目。<br>先完成一次單騎研習，你的錯題便會出現在這裏。</div>'}${items.map(q=>`<article class="mistake"><div class="row between"><span class="eyebrow">${esc(q.chapter)}</span><span class="pill">重溫 ${q.level} / 3</span></div><p>${esc(q.sentence)}</p><span class="gold">考點：${esc(q.targetWord)}</span></article>`).join('')}`;$('switch-profile').onclick=()=>profileDialog(openVault);if($('review-start'))$('review-start').onclick=()=>{game=newGame('vault',items.slice(0,30),p);begin();};}
function liveHome(){stopPolling();showView('live');$('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">同步研習 · LIVE SESSION</div><h2>烽火連營，同步進軍。</h2><p>主持人控制每題的思考、作答與揭曉。學生在可使用個人裝置時加入。</p></div></div>${DEMO?'<div class="notice">本機預覽不提供真正的多人房間。部署至 Apps Script 後，以下功能會連接你的試算表。</div>':''}<div class="mode-grid"><div class="dark-card"><div class="eyebrow">軍師主持</div><h3>建立戰役</h3><p class="teacher-note">使用首頁已選的「${esc(selectedChapter())}」，最多 ${$('count').value} 題。</p><button class="btn primary full" id="host-room" style="margin-top:22px" ${DEMO?'disabled':''}>建立六位碼房間</button></div><div class="dark-card"><div class="eyebrow">諸將集結</div><h3>加入戰役</h3><label for="room-pin" class="small muted">六位房間碼</label><input id="room-pin" maxlength="6" inputmode="numeric" placeholder="輸入房間碼" style="margin-top:8px"><button class="btn primary full" id="join-room" style="margin-top:14px" ${DEMO?'disabled':''}>領軍入營</button></div></div>`;
  $('host-room').onclick=async()=>{if(!await ensureTeacher())return;const b=$('host-room');b.disabled=true;try{const r=await rpc('createLiveRoom',teacherToken,options());live={pin:r.pin,token:r.hostToken,isHost:true};storage.set('live',live);startPolling();}catch(e){toast(e.message);b.disabled=false;}};
  $('join-room').onclick=()=>{const pin=$('room-pin').value;if(!/^\d{6}$/.test(pin)){toast('請輸入六位數字房間碼。');return;}profileDialog(async p=>{try{const r=await rpc('joinLiveRoom',pin,p);live={pin,token:r.playerToken,isHost:false};storage.set('live',live);startPolling();}catch(e){toast(e.message);}});};
  const previous=storage.get('live');if(previous&&!DEMO){const b=document.createElement('button');b.className='btn';b.style.marginTop='25px';b.textContent='接續房間 '+previous.pin;b.onclick=()=>{live=previous;startPolling();};$('live-view').appendChild(b);}}
function stopPolling(){pollEpoch++;clearTimeout(poll);poll=null;pollBusy=false;}
function startPolling(){stopPolling();showView('live');$('live-view').innerHTML='<div class="empty"><i class="loading"></i>正在偵察戰況…</div>';pollLive();}
async function refreshLive(){clearTimeout(poll);if(pollBusy){if(live)live.refresh=true;return;}await pollLive();}
async function pollLive(){if(!live||pollBusy)return;if(document.hidden){poll=setTimeout(pollLive,8000);return;}const current=live,epoch=pollEpoch;pollBusy=true;let wait=4000,finished=false;try{const r=await rpc('getLiveState',current.pin,current.token);if(live!==current||epoch!==pollEpoch)return;renderLive(r);finished=r.state.status==='FINISHED';if(finished)storage.remove('live');}catch(e){if(live!==current||epoch!==pollEpoch)return;toast(e.message);wait=8000;if(!$('live-retry')){$('live-view').innerHTML='<div class="empty">戰況暫未接通。<br><button class="btn" id="live-retry">重試連線</button> <button class="btn ghost" id="live-back">返回主營</button></div>';$('live-retry').onclick=refreshLive;$('live-back').onclick=()=>{stopPolling();live=null;showView('camp');};}}finally{if(live===current&&epoch===pollEpoch){pollBusy=false;if(!finished){const refresh=current.refresh;current.refresh=false;poll=setTimeout(pollLive,refresh?0:wait);}}}}

function renderLive(r){const s=r.state,q=r.question;const title=s.status==='WAITING'?'諸將集結':s.status==='FINISHED'?'本次戰役已結束':`第 ${s.index+1} 關 · ${PHASES[{think:0,discuss:1,answer:2,reveal:3}[s.phase]]}`;
  $('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">烽火連營 · 房間 ${esc(live.pin)}</div><h2>${title}</h2><p>${r.isHost?'你是主持人。':'你是參與將領。'}${s.status==='PLAYING'?(r.isHost?'請用下方軍令推進階段。':'等待主持人推進；每題只可提交一次。'):''}</p></div><button class="btn ghost small" id="leave-room">${r.isHost&&s.status!=='FINISHED'?'結束房間':'返回軍機處'}</button></div>${s.status==='WAITING'?`<div class="dark-card"><span class="eyebrow">集結令</span><div class="pin">${esc(live.pin)}</div><p class="muted">請同學在自己的裝置輸入以上房間碼。</p></div>`:''}<div class="roster">${r.players.map(p=>`<span class="${p.answered?'done':''}">${esc(p.name)}${p.isMe?' · 你':''}${p.answered?' ✓':''}${s.phase==='reveal'||s.status==='FINISHED'?' · '+p.score+'分':''}</span>`).join('')||'<span>等候將領加入</span>'}</div>${q&&s.status==='PLAYING'?`<article class="paper"><div class="eyebrow">${esc(q.chapter)}</div><div class="sentence">${sentenceHTML(q)}</div><p class="prompt">「${esc(q.targetWord)}」的意思是甚麼？</p><div class="options ${s.phase==='think'?'hidden':''}">${q.options.map((o,i)=>`<button class="option ${q.correct===o?'correct':''}" data-live-choice="${esc(o)}" ${r.isHost||s.phase!=='answer'||r.submitted?'disabled':''}><span class="letter">${'ABCD'[i]}</span>${esc(o)}</button>`).join('')}</div>${q.correct?`<div class="feedback">參考釋義：${esc(q.correct)}。${esc(q.explanation||'請說明這個解釋如何符合語境。')}</div>`:''}${r.submitted?'<p>軍報已交，等候揭曉。</p>':''}</article>`:''}<div class="toolbar" id="live-actions" style="margin-top:20px"></div>`;
  $('leave-room').onclick=()=>confirmAction('鳴金收兵',r.isHost?'結束房間後，所有同學會看到戰役結束。':'離開後可從烽火連營接續房間。',async()=>{if(r.isHost&&s.status!=='FINISHED')await rpc('hostLiveAction',live.pin,live.token,'close');stopPolling();live=null;showView('camp');});
  if(r.isHost&&s.status!=='FINISHED'){const action=s.status==='WAITING'?'start':({think:'discuss',discuss:'answer',answer:'reveal',reveal:'next'}[s.phase]);const label={start:'諸將已齊 · 開始',discuss:'進入商議',answer:'開放作答',reveal:'截止作答 · 揭曉',next:s.index+1>=s.count?'完成戰役':'下一關'}[action];const b=document.createElement('button');b.className='btn primary';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await rpc('hostLiveAction',live.pin,live.token,action);await refreshLive();}catch(e){toast(e.message);b.disabled=false;}};$('live-actions').appendChild(b);}
  if(r.isHost&&s.status==='WAITING'){const share=document.createElement('button');share.className='btn';share.textContent='顯示入營 QR Code';share.onclick=()=>showSharePanel(live.pin);$('live-actions').appendChild(share);}
  $$('[data-live-choice]').forEach(b=>b.onclick=async()=>{$$('[data-live-choice]').forEach(x=>x.disabled=true);try{await rpc('submitLiveAnswer',live.pin,live.token,s.index,b.dataset.liveChoice);toast('軍報已提交。');await refreshLive();}catch(e){toast(e.message);await refreshLive();}});
}
async function openTeacher(){if(!await ensureTeacher())return;showView('teacher');$('teacher-view').innerHTML='<div class="empty"><i class="loading"></i>正在整理軍情…</div>';try{const r=await rpc('getTeacherAnalytics',teacherToken,{});$('teacher-view').innerHTML=`<div class="page-head scene-head scene-teacher"><div><div class="eyebrow">軍師督學 · TEACHER REPORT</div><h2>洞察學情，調整下一步。</h2><p>${DEMO?'本機示範數據':'新版練習紀錄；原有歷史紀錄另行保留，不混算不同計分制。'}</p></div><button class="btn primary" id="import-bank">貼上新題目</button><button class="btn" id="refresh-bank">重新讀取題庫</button></div><div class="stats-grid"><div class="stat">個人練習<b>${r.totalBattles}</b></div><div class="stat">平均首答正確率<b>${r.avgAccuracy}%</b></div><div class="stat">課堂攻城<b>${r.classroomSessions}</b></div></div><div class="notice">原有歷史戰報：${r.legacyRecords} 筆 · 新版線上房間：${r.liveRooms} 間。課堂軍功與個人成績分開記錄。</div><div class="dark-card"><h3>全校常見待重溫字詞</h3>${r.difficultWords.length?r.difficultWords.map(w=>`<div class="list-row"><span>《${esc(w.chapter)}》「${esc(w.word)}」<br><small class="muted">參考：${esc(w.correct)}</small></span><span class="gold">${w.count} 筆待重溫</span></div>`).join(''):'<p class="muted">尚無足夠資料。完成個人練習後再檢視。</p>'}</div><div class="dark-card" style="margin-top:20px"><h3>最近練習</h3>${r.recent.map(x=>`<div class="list-row"><span>${esc(x.className)} · ${esc(x.number)} 號 <small class="muted">${esc(x.date.slice(0,10))}</small></span><span>${x.score} / ${x.maxScore} · 首答 ${x.accuracy}%</span></div>`).join('')||'<p class="muted">尚無練習紀錄。</p>'}</div>`;$('import-bank').onclick=openQuestionImport;$('refresh-bank').onclick=async()=>{try{boot=await rpc('refreshQuestionCache',teacherToken);renderCamp();toast('已重新讀取題庫。');}catch(e){toast(e.message);}};}catch(e){teacherToken='';$('teacher-view').innerHTML=`<div class="empty">${esc(e.message)}<br><button class="btn" id="teacher-retry">重新登入</button></div>`;$('teacher-retry').onclick=openTeacher;}}
function navigate(name){const fn=()=>{stopTimer();if(live){stopPolling();live=null;}if(name==='camp')showView('camp');else if(name==='classroom')startClassroom();else if(name==='practice')startPractice();else if(name==='vault')openVault();else if(name==='live')liveHome();else if(name==='teacher')openTeacher();};if(game&&!game.completed&&!$('battle-view').classList.contains('hidden'))confirmAction('暫離征途','目前進度會保存在此瀏覽器，重新整理後可接續。',fn);else fn();}
$('print-before').onclick=printPaper;$('chapter').onchange=updateMission;$('start-classroom').onclick=startClassroom;$('start-practice').onclick=startPractice;$('open-vault').onclick=openVault;$('open-live').onclick=liveHome;$('teacher-login').onclick=openTeacher;$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$('advance').onclick=advance;$('hint').onclick=()=>showHint();$('skip').onclick=()=>skipQuestion();$('timer-toggle').onclick=toggleTimer;$('timer-add').onclick=addTime;$('undo-score').onclick=undoScore;$('projection').onclick=()=>{document.body.classList.toggle('projection');$('projection').textContent=document.body.classList.contains('projection')?'退出投影':'投影模式';};$('quit').onclick=()=>{stopTimer();confirmAction('鳴金收兵','未完成的進度已保存在此瀏覽器。返回主營後，重新整理可接續。',()=>showView('camp'));};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='音效 '+(soundOn?'開':'關');$('sound').setAttribute('aria-pressed',soundOn);if(soundOn)sound();};
document.addEventListener('keydown',e=>{if(!$('modal').classList.contains('hidden')){if(e.key==='Tab'){const a=Array.from($('modal').querySelectorAll('input,select,textarea,button')).filter(x=>!x.disabled);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a[a.length-1].focus();}else if(!e.shiftKey&&document.activeElement===a[a.length-1]){e.preventDefault();a[0].focus();}}return;}if(/INPUT|SELECT|TEXTAREA|BUTTON/.test(document.activeElement?.tagName))return;if(!$('battle-view').classList.contains('hidden')){if(e.code==='Space'&&game?.type==='classroom'){e.preventDefault();advance();}if(e.key.toLowerCase()==='p')toggleTimer();}});
window.addEventListener('beforeunload',()=>{if(game&&!game.completed)persist();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTimer();});
function battleFlash(text){if(document.body.classList.contains('still'))return;const el=document.createElement('div');el.className='battle-flash';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),1200);}
let motion=storage.get('motion',!window.matchMedia('(prefers-reduced-motion: reduce)').matches);function applyMotion(){document.body.classList.toggle('still',!motion);$('motion').textContent='動態 '+(motion?'開':'關');$('motion').setAttribute('aria-pressed',motion);}applyMotion();$('motion').onclick=()=>{motion=!motion;storage.set('motion',motion);applyMotion();};
$('map-expand').onclick=()=>{$('campaign-map').classList.add('wide');$('map-close').focus();};$('map-close').onclick=()=>{$('campaign-map').classList.remove('wide');$('map-expand').focus();};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('campaign-map').classList.contains('wide')){$('campaign-map').classList.remove('wide');$('map-expand').focus();}});document.addEventListener('visibilitychange',()=>document.body.classList.toggle('page-hidden',document.hidden));
const LIVE_URL=PUBLIC_CONFIG.liveUrl;
let launchSearch=location.search;
const COMMANDERS=['關羽','趙雲','周瑜','黃月英'];
function readLaunchParams(){return new Promise(resolve=>{if(DEMO||REMOTE||!google.script.url?.getLocation){resolve();return;}let ended=false;const done=()=>{if(!ended){ended=true;resolve();}};const timeout=setTimeout(done,5000);google.script.url.getLocation(loc=>{if(ended)return;const q=new URLSearchParams();for(const k of ['mode','pin','chapter','count','seed'])if(loc.parameter?.[k])q.set(k,String(loc.parameter[k]).slice(0,200));launchSearch=q.toString();clearTimeout(timeout);done();});});}
function launchRoute(){const p=new URLSearchParams(launchSearch),mode=p.get('mode');if(mode==='live'){liveHome();const pin=p.get('pin');if(/^\d{6}$/.test(pin||''))$('room-pin').value=pin;return true;}if(mode==='practice'){startPractice();return true;}return false;}
function onlineLink(params={}){const u=new URL(REMOTE?PUBLIC_CONFIG.playUrl:(DEMO?LIVE_URL:(boot?.url||LIVE_URL)));u.search='';u.hash='';for(const [k,v]of Object.entries(params))if(v!==undefined&&v!=='')u.searchParams.set(k,String(v));return u.toString();}
function qrSvg(url){const q=qrcode(0,'M');q.addData(url);q.make();return q.createSvgTag({cellSize:4,margin:16,scalable:true});}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('網址已複製。');}catch(e){toast('請長按網址，選擇全選及複製。');}}
function showSharePanel(pin){const url=onlineLink(pin?{mode:'live',pin}:{});showModal(pin?'掃碼集結 · '+pin:'iPad 網上入口',`<div class="share-grid"><div class="qr-box" role="img" aria-label="遊戲入口 QR Code">${qrSvg(url)}</div><div><p>${DEMO?'此碼連到你原有的正式網址。更新 Google 部署後，該網址才會顯示新版。':pin?'同學用 iPad 相機掃描，即可前往本房間的加入頁。':'同學用 iPad 的 Safari 或 Chrome 開啟此網址即可遊玩。'}</p><label for="online-url">${pin?'房間連結':'遊戲網址'}</label><input id="online-url" value="${esc(url)}" readonly><button type="button" class="btn" id="copy-online">複製網址</button><p class="share-instruction">iPad：Safari「分享」選單 →「加入主畫面」。需要網絡連線；不用下載 App。</p></div></div>`,()=>closeModal(),'返回遊戲');$('copy-online').onclick=()=>copyText(url);}
function updateNetworkBanner(){const offline=navigator.onLine===false;$('network-banner').classList.toggle('hidden',!offline);if(offline)stopTimer();}
$('student-start').onclick=startPractice;$('student-join').onclick=liveHome;$('access-link').onclick=()=>showSharePanel();$('device-help').onclick=()=>showSharePanel();
window.addEventListener('offline',updateNetworkBanner);window.addEventListener('online',()=>{updateNetworkBanner();if(live&&!document.hidden)refreshLive();toast('網絡已恢復；未同步的戰報可按重試。');});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&live)refreshLive();});
updateNetworkBanner();

bootApp();
