'use strict';
const $=id=>document.getElementById(id), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const REMOTE=!!location.pathname?.endsWith('/play.html');
const DEMO=!REMOTE&&!(window.google&&google.script&&google.script.run);
const privateStore={getItem(k){return (DEMO?localStorage:sessionStorage).getItem(k);},setItem(k,v){return (DEMO?localStorage:sessionStorage).setItem(k,v);},removeItem(k){return (DEMO?localStorage:sessionStorage).removeItem(k);}};
const storage={get(k,d=null){try{return JSON.parse(privateStore.getItem('rtk2:'+k))??d;}catch(e){return d;}},set(k,v){try{privateStore.setItem('rtk2:'+k,JSON.stringify(v));return true;}catch(e){return false;}},remove(k){try{privateStore.removeItem('rtk2:'+k);}catch(e){}}};
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
let pollEpoch=0;let boot=null,teacherToken='',game=null,live=null,poll=null,pollBusy=false,timerHandle=null,remaining=30,timerDeadline=0,soundOn=false,audioCtx=null,modalPrevious=null,toastTimer=null,busy=false;
const TEAMS=['青龍軍','白虎軍','朱雀軍','玄武軍'];
function shuffle(a,seed){a=a.slice();let x=Number(seed)||1;const rnd=()=>{let t=x+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function chooseDemo(o){let q=DEMO_QUESTIONS.filter(q=>!o.chapter||o.chapter==='all'||q.chapter===o.chapter);if(!q.length)throw Error('此篇章暫無題目。');return shuffle(q,o.seed||Date.now()).slice(0,Math.max(1,Math.min(30,Number(o.count)||10)));}
function rpc(name,...args){return new Promise((resolve,reject)=>{
  if(DEMO){try{let r;
    if(name==='getBootstrap'){const counts={};DEMO_QUESTIONS.forEach(q=>counts[q.chapter]=(counts[q.chapter]||0)+1);r={success:true,chapters:Object.entries(counts).map(([name,count])=>({name,count})),total:DEMO_QUESTIONS.length,schools:['示範學校'],url:location.href.split('?')[0]};}
    else if(name==='getClassroomQuestions')r={success:true,questions:chooseDemo(args[1])};
    else if(name==='startPractice')r={success:true,runId:uid(),questions:chooseDemo(args[1])};
    else if(name==='savePractice'||name==='saveClassroom')r={success:true,local:true};
    else if(name==='refreshQuestionCache'){resolve(rpc('getBootstrap'));return;}
    else if(name==='getTeacherAnalytics'){const rec=storage.get('records',[]);r={success:true,totalBattles:rec.filter(x=>x.type!=='classroom').length,avgAccuracy:rec.filter(x=>x.type!=='classroom').length?Math.round(rec.filter(x=>x.type!=='classroom').reduce((n,x)=>n+(x.accuracy||0),0)/rec.filter(x=>x.type!=='classroom').length):0,legacyRecords:0,classroomSessions:rec.filter(x=>x.type==='classroom').length,liveRooms:0,difficultWords:[],recent:rec.filter(x=>x.type!=='classroom').slice(-20).reverse().map(x=>({date:x.date,className:x.profile?.studentClass||'課堂',number:x.profile?.studentNumber||'',score:x.score||0,maxScore:x.maxScore||0,accuracy:x.accuracy||0}))};}
    else throw Error('此功能須在已部署的 Google Apps Script 網址使用；本機預覽不會建立真正線上房間。');
    resolve(r);
  }catch(e){reject(e);}return;}
  if(REMOTE){remoteTransport.call(name,args).then(r=>r?.success===false?reject(Error(r.error||'操作未完成。')):resolve(r),reject);return;}
  let settled=false;const timeout=setTimeout(()=>{if(!settled){settled=true;reject(Error('連線較慢，請重試。已提交的戰報會按同一編號核對，避免重複記分。'));}},30000);
  google.script.run.withSuccessHandler(r=>{if(settled)return;settled=true;clearTimeout(timeout);if(r&&r.success===false)reject(Error(r.error||'操作未完成。'));else resolve(r);}).withFailureHandler(e=>{if(settled)return;settled=true;clearTimeout(timeout);reject(Error(e.message||String(e)));})[name](...args);
});}
function toast(s){clearTimeout(toastTimer);$('toast').textContent=s;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),5000);}
function sound(ok=true){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.frequency.value=ok?523:220;g.gain.setValueAtTime(.04,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.2);o.start();o.stop(audioCtx.currentTime+.2);}catch(e){}}
function showView(name){if(name!=='battle'){$('projection').textContent='投影模式';}$$('.view').forEach(el=>el.classList.toggle('hidden',el.id!==name+'-view'));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name||(name==='battle'&&b.dataset.nav===(game?.type==='classroom'?'classroom':'practice'))));if(name!=='battle')document.body.classList.remove('projection');window.scrollTo(0,0);}
function showModal(title,body,onSubmit,label='確定'){
  modalPrevious=document.activeElement;$('modal').innerHTML=`<form class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">${esc(title)}</h2>${body}<p id="modal-error" class="error-text" style="margin-top:12px"></p><div class="actions"><button type="button" class="btn ghost" id="modal-cancel">取消</button><button type="submit" class="btn primary" id="modal-submit">${esc(label)}</button></div></form>`;
  $('modal').classList.remove('hidden');$('modal-cancel').onclick=closeModal;
  $('modal').querySelector('form').onsubmit=async e=>{e.preventDefault();$('modal-submit').disabled=true;try{await onSubmit(new FormData(e.target));}catch(err){if($('modal-error'))$('modal-error').textContent=err.message;else toast(err.message);}finally{if($('modal-submit'))$('modal-submit').disabled=false;}};
  $('modal').querySelector('input,select,textarea,button').focus();
}
function closeModal(){$('modal').classList.add('hidden');$('modal').innerHTML='';modalPrevious?.focus();}
function confirmAction(title,text,fn){showModal(title,`<p>${esc(text)}</p>`,async()=>{closeModal();await fn();},'確認');}
async function ensureTeacher(){if(teacherToken)return true;if(DEMO){teacherToken='demo';return true;}return new Promise(resolve=>{
  showModal('軍師驗印','<p>教師主持、軍情報告及開設線上房間需要驗證。</p><label for="teacher-pass">教師密碼</label><input id="teacher-pass" name="password" type="password" autocomplete="current-password" required>',async f=>{const r=await rpc('teacherLogin',f.get('password'));teacherToken=r.token;closeModal();resolve(true);},'驗印入營');
  $('modal-cancel').onclick=()=>{closeModal();resolve(false);};
});}
function profileDialog(callback){const p=storage.get('profile',{});showModal('將領入冊',`<p>建議使用代號。錯題保存在此瀏覽器；共用電腦請使用自己的班別和學號。</p><label for="student-school">學校</label><select id="student-school" name="studentSchool">${(boot?.schools||['示範學校']).map(s=>`<option ${p.studentSchool===s?'selected':''}>${esc(s)}</option>`).join('')}</select><div class="two"><div><label for="student-class">班別</label><input id="student-class" name="studentClass" value="${esc(p.studentClass||'2A')}" maxlength="12" required></div><div><label for="student-num">學號</label><input id="student-num" name="studentNumber" value="${esc(p.studentNumber||'')}" inputmode="numeric" pattern="[0-9]{1,3}" maxlength="3" required></div></div><label for="student-name">將領代號（選填）</label><input id="student-name" name="studentName" value="${esc(p.studentName||'')}" maxlength="30"><p style="margin-top:17px">選擇你的軍團</p><div class="commander-grid" role="group" aria-label="選擇軍團">${TEAMS.map((t,i)=>`<label class="commander-choice"><input type="radio" name="studentTeam" value="${t}" ${(p.studentTeam||TEAMS[0])===t?'checked':''}><span class="commander-art" style="--commander:var(--asset${i})" aria-hidden="true"></span><span>${t}<small>${COMMANDERS[i]}</small></span></label>`).join('')}</div>`,async f=>{const p=Object.fromEntries(f);p.studentClass=p.studentClass.replace(/\s/g,'').toUpperCase();p.studentNumber=String(Number(p.studentNumber)).padStart(2,'0');storage.set('profile',p);closeModal();await callback(p);},'整備出發');}
function options(){return {chapter:$('chapter').value,count:Number($('count').value),seed:Number(new URLSearchParams(launchSearch).get('seed'))||Date.now(),mode:'practice'};}
function selectedChapter(){return $('chapter').value==='all'?'全篇混合':$('chapter').value;}
async function bootApp(){
  try{const initial=await Promise.all([rpc('getBootstrap'),readLaunchParams()]);boot=initial[0];renderCamp();$('connection').innerHTML=`<span class="dot"></span>${DEMO?'本機示範':'軍情已接通'}`;$('footer-status').textContent=`${DEMO?'示範題庫 · 不連接原有試算表':'校本題庫 · Google Sheets'} · ${boot.total} 題`;
    if(DEMO){$('boot-notice').textContent='本機預覽｜使用內附選擇題及六款互動示例；課堂攻城及個人研習可操作，雲端成績及線上房間須部署後使用。';$('boot-notice').classList.remove('hidden');}
    else if(!boot.total){$('boot-notice').textContent='題庫目前沒有有效題目。請檢查 QuestionBank 的七個基本欄位；系統不會覆蓋原有資料。';$('boot-notice').classList.remove('hidden');}
    const unsynced=storage.get('pending');if(unsynced&&!storage.get('active')){const b=document.createElement('button');b.className='btn small';b.textContent='接續同步上次戰報';b.onclick=()=>{game=unsynced;renderResult();syncResult();};$('boot-notice').appendChild(b);$('boot-notice').classList.remove('hidden');}const routed=launchRoute();const pending=storage.get('active');if(!routed&&pending?.questions?.length){showModal('接續未完的征途','<p>找到此瀏覽器尚未完成的進度。可以接續，或取消後開新局。</p>',()=>{game=pending;closeModal();showView('battle');renderQuestion();},'接續征途');}
  }catch(e){$('connection').textContent='題庫未接通';$('boot-notice').innerHTML=`${esc(e.message)} <button class="btn small" id="retry-boot">重試連線</button>`;$('boot-notice').classList.remove('hidden');$('retry-boot').onclick=bootApp;}
}
function renderCamp(){const old=$('chapter').value;const requested=new URLSearchParams(launchSearch).get('chapter');$('chapter').innerHTML='<option value="all">全部篇章 · 混合挑戰</option>'+boot.chapters.map(c=>`<option value="${esc(c.name)}">${esc(c.name)} · ${c.count} 題</option>`).join('');$('chapter').value=boot.chapters.some(c=>c.name===(requested||old))?(requested||old):'all';
  const countParam=Number(new URLSearchParams(launchSearch).get('count'));if(countParam>=1&&countParam<=30){if(!Array.from($('count').options).some(o=>Number(o.value)===countParam))$('count').add(new Option(countParam+' 關 · 同題挑戰',countParam));$('count').value=countParam;}
  $('bank-total').textContent=boot.total+' 題';$('footer-status').textContent=`${DEMO?'示範題庫 · 不連接原有試算表':'校本題庫 · Google Sheets'} · ${boot.total} 題`;renderLibrary();$('start-classroom').disabled=$('start-practice').disabled=!boot.total;
  const spots=[[16,77],[34,63],[51,53],[66,37],[84,27],[65,77]],names=['成都','漢中','祁山','天水','長安','荊州'];
  $('cities').innerHTML=boot.chapters.slice(0,6).map((c,i)=>`<button class="city" style="left:${spots[i][0]}%;top:${spots[i][1]}%" data-chapter="${esc(c.name)}" aria-label="${names[i]}：研習${esc(c.name)}"><svg class="fort-svg" viewBox="0 0 80 62" aria-hidden="true"><ellipse cx="40" cy="52" rx="33" ry="8" fill="#0b201a66"/><path d="M10 32 39 21 70 34 41 47Z" fill="#897c5d" stroke="#d4c18f"/><path d="M10 32 10 47 41 60 41 47Z" fill="#a19370" stroke="#d5c390"/><path d="M41 47 70 34 70 48 41 60Z" fill="#625e4d" stroke="#b5a580"/><path d="M18 33 18 23 40 15 59 23 59 36 40 43Z" fill="#6e6952" stroke="#dfcca1"/><path d="M14 24 40 10 65 24 42 31Z" fill="#344637" stroke="#b29b61"/><path d="M24 16 40 6 57 16 40 23Z" fill="#3b4c3d" stroke="#dbc184"/><path d="M31 32 31 41 40 45 40 36Z" fill="#2a3127"/><path d="M10 32 10 28 16 26 16 30 M21 29 21 25 26 23 26 27 M54 41 54 37 60 35 60 39 M65 37 65 33 70 31 70 35" stroke="#dfc897" stroke-width="3" fill="none"/></svg><span class="city-flag">${i<3?'蜀':'魏'}</span><span class="city-name">${names[i]}</span><small>${esc(c.name)}</small></button>`).join('');$$('.city').forEach(b=>b.onclick=()=>{$('chapter').value=b.dataset.chapter;updateMission();});updateMission();}
function updateMission(){$('mission-title').textContent=selectedChapter();if($('home-mission'))$('home-mission').textContent=(selectedChapter()==='全篇混合'?'全篇混合短練':'《'+selectedChapter()+'》字詞辨義')+' · '+$('count').value+' 題';$$('.city').forEach(b=>b.classList.toggle('selected',b.dataset.chapter===$('chapter').value));}
function navigate(name){const fn=()=>{stopTimer();if(live){stopPolling();live=null;}if(name==='camp')showView('camp');else if(name==='classroom')startClassroom();else if(name==='practice')startPractice();else if(name==='vault')openVault();else if(name==='live')liveHome();else if(name==='teacher')openTeacher();};if(game&&!game.completed&&!$('battle-view').classList.contains('hidden'))confirmAction('暫離征途','目前進度會保存在此瀏覽器，重新整理後可接續。',fn);else fn();}
$('print-before').onclick=printPaper;$('chapter').onchange=()=>{updateMission();renderLibrary();};$('start-classroom').onclick=startClassroom;$('start-practice').onclick=startPractice;$('open-vault').onclick=openVault;$('open-live').onclick=liveHome;$('teacher-login').onclick=openTeacher;$$('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$('advance').onclick=advance;$('hint').onclick=()=>showHint();$('skip').onclick=()=>skipQuestion();$('timer-toggle').onclick=toggleTimer;$('timer-add').onclick=addTime;$('undo-score').onclick=undoScore;$('projection').onclick=()=>{document.body.classList.toggle('projection');$('projection').textContent=document.body.classList.contains('projection')?'退出投影':'投影模式';};$('quit').onclick=()=>{stopTimer();confirmAction('鳴金收兵','未完成的進度已保存在此瀏覽器。返回主營後，重新整理可接續。',()=>showView('camp'));};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').textContent='音效 '+(soundOn?'開':'關');$('sound').setAttribute('aria-pressed',soundOn);if(soundOn)sound();};
document.addEventListener('keydown',e=>{if(!$('modal').classList.contains('hidden')){if(e.key==='Tab'){const a=Array.from($('modal').querySelectorAll('input,select,textarea,button')).filter(x=>!x.disabled);if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a[a.length-1].focus();}else if(!e.shiftKey&&document.activeElement===a[a.length-1]){e.preventDefault();a[0].focus();}}return;}if(/INPUT|SELECT|TEXTAREA|BUTTON/.test(document.activeElement?.tagName))return;if(!$('battle-view').classList.contains('hidden')){if(e.code==='Space'&&game?.type==='classroom'){e.preventDefault();advance();}if(e.key.toLowerCase()==='p')toggleTimer();}});
window.addEventListener('beforeunload',()=>{if(game&&!game.completed)persist();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTimer();});
function battleFlash(text){if(document.body.classList.contains('still'))return;const el=document.createElement('div');el.className='battle-flash';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),1200);}
let motion=storage.get('motion',!window.matchMedia('(prefers-reduced-motion: reduce)').matches);function applyMotion(){document.body.classList.toggle('still',!motion);$('motion').textContent='動態 '+(motion?'開':'關');$('motion').setAttribute('aria-pressed',motion);}applyMotion();$('motion').onclick=()=>{motion=!motion;storage.set('motion',motion);applyMotion();};
$('map-expand').onclick=()=>{$('campaign-map').classList.add('wide');$('map-close').focus();};$('map-close').onclick=()=>{$('campaign-map').classList.remove('wide');$('map-expand').focus();};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('campaign-map').classList.contains('wide')){$('campaign-map').classList.remove('wide');$('map-expand').focus();}});document.addEventListener('visibilitychange',()=>document.body.classList.toggle('page-hidden',document.hidden));
const LIVE_URL=PUBLIC_CONFIG.liveUrl;
let launchSearch=location.search;
const COMMANDERS=['關羽','趙雲','周瑜','黃月英'];
function readLaunchParams(){return new Promise(resolve=>{if(DEMO||REMOTE||!google.script.url?.getLocation){resolve();return;}let ended=false;const done=()=>{if(!ended){ended=true;resolve();}};const timeout=setTimeout(done,5000);google.script.url.getLocation(loc=>{if(ended)return;const q=new URLSearchParams();for(const k of ['mode','pin','chapter','count','seed'])if(loc.parameter?.[k])q.set(k,String(loc.parameter[k]).slice(0,200));launchSearch=q.toString();clearTimeout(timeout);done();});});}
function launchRoute(){const p=new URLSearchParams(launchSearch),mode=p.get('mode');if(mode==='live'){liveHome();const pin=p.get('pin');if(/^\d{6}$/.test(pin||''))$('room-pin').value=pin;return true;}if(mode==='practice'){startPractice();return true;}return false;}
function onlineLink(params={}){const u=new URL(REMOTE?PUBLIC_CONFIG.playUrl:(DEMO?LIVE_URL:(boot?.url||LIVE_URL)));u.search='';u.hash='';for(const [k,v]of Object.entries(params))if(v!==undefined&&v!=='')u.searchParams.set(k,String(v));return u.toString();}
function qrSvg(url){const q=qrcode(0,'M');q.addData(url);q.make();return q.createSvgTag({cellSize:4,margin:16,scalable:true});}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('網址已複製。');}catch(e){toast('請長按網址，選擇全選及複製。');}}
function showSharePanel(pin){const url=onlineLink(pin?{mode:'live',pin}:{});showModal(pin?'掃碼集結 · '+pin:'iPad 網上入口',`<div class="share-grid"><div class="qr-box" role="img" aria-label="遊戲入口 QR Code">${qrSvg(url)}</div><div><p>${DEMO?'此碼連到你原有的正式網址。更新 Google 部署後，該網址才會顯示新版。':pin?'同學用 iPad 相機掃描，即可前往本房間的加入頁。':'同學用 iPad 的 Safari 或 Chrome 開啟此網址即可遊玩。'}</p><label for="online-url">${pin?'房間連結':'遊戲網址'}</label><input id="online-url" value="${esc(url)}" readonly><button type="button" class="btn" id="copy-online">複製網址</button><p class="share-instruction">iPad：Safari「分享」選單 →「加入主畫面」。需要網絡連線；不用下載 App。</p></div></div>`,()=>closeModal(),'返回遊戲');$('copy-online').onclick=()=>copyText(url);}
function updateNetworkBanner(){const offline=navigator.onLine===false;$('network-banner').classList.toggle('hidden',!offline);if(offline)stopTimer();}
$('student-start').onclick=startPractice;$('student-join').onclick=liveHome;$('access-link').onclick=()=>showSharePanel();$('device-help').onclick=()=>showSharePanel();
$('home-task-start').onclick=()=>{if($('count'))$('count').value='5';startPractice();};
$('home-review-start').onclick=openVault;
$('home-choose-unit').onclick=()=>{const panel=document.querySelector('.advanced-learning');if(panel){panel.open=true;panel.scrollIntoView({behavior:document.body.classList.contains('still')?'auto':'smooth',block:'start'});setTimeout(()=>$('chapter').focus(),250);}};
$('quick-room-pin').oninput=e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,6);};
$('quick-room-pin').onkeydown=e=>{if(e.key==='Enter')$('quick-join').click();};
$('quick-join').onclick=()=>{const pin=$('quick-room-pin').value.trim();if(!/^\d{6}$/.test(pin)){toast('請輸入六位數字房間碼。');$('quick-room-pin').focus();return;}liveHome();$('room-pin').value=pin;$('join-room').click();};
window.addEventListener('offline',updateNetworkBanner);window.addEventListener('online',()=>{updateNetworkBanner();if(live&&!document.hidden)refreshLive();toast('網絡已恢復；未同步的戰報可按重試。');});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&live)refreshLive();});
updateNetworkBanner();

initLearning();
WarMusic.init();
bootApp();
