/* Competition derives progress from submitted answers, never from answer correctness. */
const Competition = {
  standings(players) {
    const rows=players.map((p,i)=>({...p,score:Number(p.score)||0,original:i}));
    const timed=p=>p.score>0&&rows.filter(x=>x.score===p.score).every(x=>Number.isFinite(x.elapsedMs));
    rows.forEach(p=>p.timeRanked=timed(p));
    rows.sort((a,b)=>b.score-a.score||(a.timeRanked?a.elapsedMs-b.elapsedMs:0)||a.original-b.original);
    rows.forEach((p,i)=>p.rank=i&&p.score===rows[i-1].score&&(!p.timeRanked||p.elapsedMs===rows[i-1].elapsedMs)?rows[i-1].rank:i+1);
    return rows;
  },
  summary(players){const total=players.length,submitted=players.filter(p=>p.answered).length;return {total,submitted,remaining:total-submitted,percent:total?Math.round(submitted/total*100):0};},
  questionKey(r){return JSON.stringify([r.state,r.question,r.isHost,r.submitted]);}
};
function marchGraphic(percent){const value=Math.max(0,Math.min(100,Number(percent)||0));return '<div class="battlefield-scene" role="img" aria-label="諸軍行軍：本輪交卷進度 '+value+'%"><div class="battlefield-landscape" aria-hidden="true"></div><div class="battlefield-shade" aria-hidden="true"></div><div class="battlefield-unit" style="left:'+value*.72+'%" aria-hidden="true"></div><div class="battlefield-caption"><span>軍情即報</span><strong>'+(value===100?'諸軍備戰就緒':'諸軍集結 · 靜候軍令')+'</strong><small>交卷進度 '+value+'% · 以實際軍報推進</small></div><div class="battlefield-progress"><i style="width:'+value+'%"></i></div></div>';}
function competitionBoard(r){
  if(r.state.mode==='race')return raceBoard(r);
  if(r.state.mode==='teacher')return teacherLiveBoard(r);
  const c=Competition.summary(r.players),s=r.state,ranked=Competition.standings(r.players),reveal=s.phase==='reveal'||s.status==='FINISHED';
  return `<section class="war-board" aria-label="全班戰況"><div class="war-heading"><div><span class="eyebrow">軍情即報 · 全班戰況</span><h3>${s.status==='WAITING'?'諸將集結':s.status==='FINISHED'?'本役軍功榜':'第 '+(s.index+1)+' 關 · 軍報進度'}</h3></div><strong class="war-count">${s.status==='WAITING'?c.total+' 人入營':c.submitted+' / '+c.total+' 已交'}</strong></div>${marchGraphic(c.percent)}<div class="war-meter" role="progressbar" aria-label="本題交卷進度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${c.percent}"><i style="width:${c.percent}%"></i></div><p class="war-status" role="status">${s.status==='WAITING'?'等候軍師開始':c.remaining?c.remaining+' 人尚未交卷；留時間讀原文。':'本輪軍報已齊；由軍師決定何時揭曉。'} · 每約 4 秒同步，網絡慢時會延後。</p><div class="war-ranks">${ranked.map(p=>`<div class="war-lane ${p.isMe?'is-me':''}"><span class="war-place">${p.rank}</span><div class="war-general"><b>${esc(p.name)}${p.isMe?' · 你':''}</b><div class="war-track"><i style="width:${Math.min(100,p.score/Math.max(3,(s.count||1)*3)*100)}%"></i></div></div><strong>${p.score} 分${p.score>0&&Number.isFinite(p.elapsedMs)?`<small class="war-time">答對用時 ${p.elapsedMs/1000} 秒</small>`:""}</strong><span class="war-tag ${p.answered?'done':''}">${s.status==='WAITING'?'已入營':p.answered?'軍報已交':'尚未交卷'}</span></div>`).join('')||'<p>等候將領加入。</p>'}</div><p class="muted">${reveal?'本輪分數已計入；先比分數，同分比答對用時。':'排名只計已揭曉題目；已交不代表答對。'} 答對每題 3 分；同分時，答對題目的累積用時較短者排前。由開放作答計時，取整秒；網絡延遲可能影響結果。舊紀錄沒有時間則同分並列。</p>${r.isHost?'<p class="teacher-note">主持提示：交卷比例偏低時先留讀題時間；揭曉後抽一位同學指出原文證據。</p>':''}</section>`;
}

function raceBoard(r){const ranked=Competition.standings(r.players),count=r.state.count||1,progress=r.players.reduce((n,p)=>n+(p.progress||0),0),percent=r.players.length?Math.round(progress/(r.players.length*count)*100):0;return '<section class="war-board"><div class="war-heading"><h3>'+(r.state.status==='FINISHED'?'本役軍功榜':'諸軍競速 · 即時戰況')+'</h3><strong>'+r.players.filter(p=>p.finished).length+' / '+r.players.length+' 人完成</strong></div>'+marchGraphic(percent)+'<div class="war-ranks">'+ranked.map(p=>'<div class="war-lane '+(p.isMe?'is-me':'')+'"><span class="war-place">'+p.rank+'</span><div class="war-general"><b>'+esc(p.name)+(p.isMe?' · 你':'')+'</b><div class="war-track"><i style="width:'+(p.progress||0)/count*100+'%"></i></div><small>完成 '+(p.progress||0)+' / '+count+' 題</small></div><strong>'+p.score+' 分<small class="war-time">答對用時 '+Math.round((p.elapsedMs||0)/1000)+' 秒</small></strong><span class="war-tag '+(p.finished?'done':'')+'">'+(p.finished?'凱旋':r.state.status==='WAITING'?'已入營':'進軍中')+'</span></div>').join('')+'</div><p>首次答對 3 分；背水一戰再試答對 1 分。先比分數，同分比答對用時。戰況約每 3 秒更新，網絡延遲可能影響用時。</p></section>';}

function teamGainCards(teams){return '<section class="team-gain-board" aria-label="本題各軍軍功"><h3>本題軍功 · 諸軍論賞</h3><div class="team-gain-grid">'+teams.map((t,i)=>'<article class="team-gain '+(t.roundPoints>0?'earned':'')+'" style="--reveal-delay:'+i*.12+'s"><i class="team-avatar" style="--commander:var(--asset'+i%4+')" aria-hidden="true"></i><strong>'+esc(t.name)+'</strong><b class="gain-number">＋'+(t.roundPoints||0)+'</b><span>累積 '+t.score+' 分</span></article>').join('')+'</div></section>';}
function teacherLiveBoard(r){const c=Competition.summary(r.players),ranked=Competition.standings(r.players),reveal=r.state.phase==='reveal'||r.state.status==='FINISHED';return '<section class="war-board"><div class="war-heading"><h3>四軍戰況 · '+(reveal?'本題軍功已計入':'交卷進度')+'</h3><strong>'+c.submitted+' / '+c.total+' 已交</strong></div>'+marchGraphic(c.percent)+'<div class="team-progress-grid">'+(r.teams||[]).map((t,i)=>'<div class="team-progress"><strong>'+esc(t.name)+'</strong><span>'+t.answered+' / '+t.members+' 已交</span><div class="war-track"><i style="width:'+(t.members?t.answered/t.members*100:0)+'%"></i></div><b>'+t.score+' 分</b></div>').join('')+'</div><div class="war-ranks">'+ranked.map(p=>'<div class="war-lane '+(p.isMe?'is-me':'')+'"><span class="war-place">'+p.rank+'</span><div class="war-general"><b>'+esc(p.name)+(p.isMe?' · 你':'')+'</b><small>'+esc(p.team)+'</small></div><strong>'+p.score+' 分'+(reveal?'<small class="round-points">本題 ＋'+p.roundPoints+'</small>':'')+'</strong><span class="war-tag '+(p.answered?'done':'')+'">'+(p.answered?'已交卷':'待作答')+'</span></div>').join('')+'</div><p>各軍分數為隊員軍功總和；個人先比分數，同分比答對用時。首次答對 3 分，背水一戰重答成功 1 分。約每 3 秒同步。</p></section>';}
