/* Multiplayer flow is independent from the teacher-operated four-team classroom. */
const LIVE_PHASE_NAMES={think:'準備作答',discuss:'準備作答',answer:'作答中',reveal:'答案與戰況'};
function transientLiveError_(e){return /同時連線|系統正在排隊|軍報繁忙|Service invoked too many times|Server error|NetworkError|Failed to fetch|逾時|timeout/i.test(String(e?.message||e));}
function liveDelay_(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function liveRpc_(name,args,attempts=4){let last;for(let i=0;i<attempts;i++){try{return await rpc(name,...args);}catch(e){last=e;if(!transientLiveError_(e)||i===attempts-1)throw e;await liveDelay_(700*Math.pow(2,i)+Math.floor(Math.random()*350));}}throw last;}
function livePollDelay_(failed=false,random=Math.random()){return failed?7000+Math.floor(random()*3000):4500+Math.floor(random()*1500);}
function liveHome(){stopPolling();showView('live');$('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">同步競答 · LIVE QUIZ</div><h2>烽火連營，同步競答。</h2><p>每人用自己的裝置作答。先比分數，同分再比答對用時。</p></div></div>${DEMO?'<div class="notice">示範版沒有真正多人房間，請使用正式網上入口。</div>':''}<div class="mode-grid"><div class="dark-card"><h3>老師主持</h3><p>「${esc(selectedChapter())}」· 最多 ${$('count').value} 題</p><p>開始作答 → 老師揭曉各軍得分 → 老師按下一題。</p><button class="btn primary full" id="host-room" ${DEMO?'disabled':''}>建立六位碼房間</button></div><div class="dark-card"><h3>學生加入</h3><label for="room-pin">六位房間碼</label><input id="room-pin" maxlength="6" inputmode="numeric" placeholder="輸入房間碼"><button class="btn primary full" id="join-room" ${DEMO?'disabled':''}>加入競答</button></div></div>`;
  $('host-room').onclick=async()=>{if(!await ensureTeacher())return;const b=$('host-room');if(!b)return;b.disabled=true;try{const r=await rpc('createLiveRoom',teacherToken,{...options(),mode:'teacher'});live={pin:r.pin,token:r.hostToken,isHost:true};storage.set('live',live);startPolling();}catch(e){toast(e.message);b.disabled=false;}};
  $('join-room').onclick=()=>{const pin=$('room-pin').value.trim();if(!/^\d{6}$/.test(pin)){toast('請輸入六位數字房間碼。');return;}const previous=storage.get('live');if(previous?.pin===pin&&!previous.isHost){live=previous;startPolling();return;}profileDialog(async p=>{try{$('live-view').innerHTML='<div class="empty">正在加入房間…</div>';const clientToken=uid()+uid();const r=await liveRpc_('joinLiveRoom',[pin,p,clientToken]);live={pin,token:r.playerToken,isHost:false};storage.set('live',live);startPolling();}catch(e){liveHome();$('room-pin').value=pin;toast(e.message);}});};
  const previous=storage.get('live');if(previous&&!DEMO){const b=document.createElement('button');b.className='btn';b.textContent='重新連線 · 房間 '+previous.pin;b.onclick=()=>{live=previous;startPolling();};$('live-view').appendChild(b);}}
let liveAutoTimer=null,liveAutoKey='',liveHostBusy=false;
function stopPolling(){pollEpoch++;clearTimeout(poll);clearTimeout(liveAutoTimer);liveAutoTimer=null;liveAutoKey='';poll=null;pollBusy=false;}
function startPolling(){stopPolling();lastLiveRender='';lastLiveQuestion='';showView('live');$('live-view').innerHTML='<div class="empty"><i class="loading"></i>正在接通房間…</div>';pollLive();}
async function refreshLive(){clearTimeout(poll);if(pollBusy){if(live)live.refresh=true;return;}await pollLive();}
async function pollLive(){if(!live||pollBusy)return;if(document.hidden){poll=setTimeout(pollLive,8000);return;}const current=live,epoch=pollEpoch;pollBusy=true;let wait=livePollDelay_(),finished=false;try{const r=await rpc('getLiveState',current.pin,current.token);if(live!==current||epoch!==pollEpoch)return;renderLive(r);finished=r.state.status==='FINISHED';if(finished)storage.remove('live');}catch(e){if(live!==current||epoch!==pollEpoch)return;toast(e.message);lastLiveRender='';lastLiveQuestion='';wait=livePollDelay_(true);if(!$('live-retry')){$('live-view').innerHTML='<div class="empty">連線暫時中斷，房間資料仍保留。<br><button class="btn" id="live-retry">重新連線</button> <button class="btn ghost" id="live-back">返回主營</button></div>';$('live-retry').onclick=refreshLive;$('live-back').onclick=()=>{stopPolling();live=null;showView('camp');};}}finally{if(live===current&&epoch===pollEpoch){pollBusy=false;if(!finished){const refresh=current.refresh;current.refresh=false;poll=setTimeout(pollLive,refresh?0:wait);}}}}

async function advanceLiveHost(r){if(liveHostBusy)return;liveHostBusy=true;try{const s=r.state,action=s.status==='WAITING'?'start':s.phase==='reveal'?'next':s.phase==='answer'?'reveal':'answer';await rpc('hostLiveAction',live.pin,live.token,action);await refreshLive();}catch(e){toast(e.message);}finally{liveHostBusy=false;}}
function liveMini(r){const c=Competition.summary(r.players),me=Competition.standings(r.players).find(p=>p.isMe);return '<div class="live-mini"><strong>'+(r.state.status==='WAITING'?c.total+' 人已入營':c.submitted+' / '+c.total+' 人已交卷')+'</strong><span>'+(r.isHost?'老師揭曉後，才公開本題得分':me?'你：'+me.score+' 分 · 第 '+me.rank+' 位':'')+'</span></div>';}
const RACE_TOOLS={hint:['孔明點撥','借東風，尋文脈','扇'],clue:['破陣辨疑','去偽存真，尋得線索','破'],rally:['背水一戰','答錯可再試一次','盾']};
function stratagems(r){return '<section class="stratagems" aria-label="三大錦囊"><div class="eyebrow">軍師授策 · 每場各一次</div><div class="stratagem-grid">'+Object.entries(RACE_TOOLS).map(([k,v])=>'<button class="stratagem '+k+'" data-stratagem="'+k+'" '+(r.tools?.[k]?'disabled':'')+'><span class="stratagem-art" aria-hidden="true"></span><strong>'+v[0]+'</strong><small>'+(r.tools?.[k]?'本場已用':v[1])+'</small></button>').join('')+'</div>'+Object.entries(r.tools||{}).filter(([k,t])=>t.index===r.state.index).map(([k,t])=>'<div class="stratagem-note '+k+'" role="status"><b>'+RACE_TOOLS[k][0]+'</b> · '+esc(t.text)+'</div>').join('')+(r.retryPending?'<div class="stratagem-note rally" role="alert">背水一戰！剛才未答對，請再想一想。這次答對可得 1 分。</div>':'')+'</section>';}
function liveOutcome(r){if(r.isHost)return '';const o=r.lastResult,done=r.state.status==='FINISHED',me=Competition.standings(r.players).find(p=>p.isMe);if(!o)return r.submitted?'<div class="live-outcome waiting" role="status">⚑ 答案已收到 · 等候老師揭曉。你可以查看各軍交卷進度。</div>':'';return '<div class="live-outcome '+(o.correct?'victory':'rally')+'" role="status"><span class="live-emblem" aria-hidden="true">'+(done?'♛':o.correct?'⚑':'策')+'</span><strong>'+(done?(me?.rank===1?'本役第一 · 凱旋！':'戰役結束'):o.correct?(o.streak>=2?o.streak+' 連捷！答對':'✓ 答對 · 進軍！'):'✕ 本題未答對 · 下題再戰')+'</strong><p>本題 ＋'+o.points+' 分 · 你的答案：'+esc(o.choice||'未作答')+'</p><p>正確答案：'+esc(o.answer)+'</p><p>'+esc(o.explanation)+'</p><p>'+(done?'先比分數，同分比答對用時。':'等候老師按下一題。')+'</p></div>';}
let lastLiveRender='',lastLiveQuestion='';
function renderLive(r){
  if(r.lastResult&&live.lastFeedback!==r.lastResult.index){live.lastFeedback=r.lastResult.index;storage.set('live',live);sound(r.lastResult.correct);if(r.lastResult.correct)battleFlash(r.lastResult.streak>=2?r.lastResult.streak+' 連捷！':'答對 · 進軍！');}const signature=JSON.stringify(r);if(signature===lastLiveRender)return;
  const key=Competition.questionKey(r)+JSON.stringify([r.tools,r.retryPending,r.finished]);if(lastLiveQuestion===key&&document.getElementById('competition-board')){$('competition-board').innerHTML=competitionBoard(r);$('live-mini').innerHTML=liveMini(r);lastLiveRender=signature;return;}
  const s=r.state,q=r.question,title=s.status==='WAITING'?'已入房 · 等候老師開始':s.status==='FINISHED'?'本次戰役已結束':`第 ${s.index+1} / ${s.count} 題 · ${s.phase==='reveal'?'軍功揭曉':'作答中'}`;
  $('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">烽火連營 · 房間 ${esc(live.pin)}</div><h2>${title}</h2><p>${r.isHost?'按「揭曉軍功」公佈答案及各軍加分，再按「下一題」。':s.status==='WAITING'?'你已成功加入；老師開始後，題目會自動出現。':'交卷後等候老師揭曉。首次答對 3 分；同分再比答對用時。'}</p></div><button class="btn ghost small" id="leave-room">${r.isHost&&s.status!=='FINISHED'?'結束房間':'返回主營'}</button></div><div id="live-actions" class="toolbar live-host-controls"></div>${s.status==='WAITING'&&r.isHost?`<div class="dark-card"><span class="eyebrow">六位房間碼</span><div class="pin">${esc(live.pin)}</div><p>請學生在自己的裝置選「加入課堂」，輸入此碼。</p></div>`:''}<div id="live-mini">${liveMini(r)}</div>${liveOutcome(r)}${(s.phase==='reveal'||s.status==='FINISHED')&&r.teams?teamGainCards(r.teams):''}${q&&!r.isHost&&s.phase==='answer'&&!r.submitted?stratagems(r):''}${q&&s.status==='PLAYING'?`<article class="paper live-question"><div class="eyebrow">${esc(q.chapter)}</div><div class="sentence">${sentenceHTML(q)}</div><p class="prompt">${q.kind?esc(IQ.names[q.kind]):'「'+esc(q.targetWord)+'」的意思是甚麼？'}</p><div class="options">${q.options.map((o,i)=>`<button class="option ${q.correct===o?'correct':''}" data-live-choice="${esc(o)}" ${r.isHost||s.phase!=='answer'||r.submitted||r.tools?.clue?.index===s.index&&r.tools.clue.removedOption===o?'disabled':''}><span class="letter">${'ABCD'[i]}</span>${esc(o)}</button>`).join('')}</div>${q.correct!==undefined?`<div class="feedback">參考答案：${esc(answerText(q))}。${esc(q.explanation||'請指出原文依據。')}</div>`:''}</article>`:''}${r.review?.length?`<details class="paper"><summary>戰後復盤 · 查看每題答案與解析</summary>${r.review.map(x=>`<div class="feedback"><strong>第 ${x.index+1} 題 · ${x.correct?'答對':'待鞏固'}</strong><p>${sentenceHTML({sentence:x.prompt})}</p><p>參考答案：${esc(x.answer)}</p><p>${esc(x.explanation)}</p></div>`).join('')}</details>`:''}<details class="live-standings" open><summary>軍功榜及同學進度</summary><div id="competition-board">${competitionBoard(r)}</div></details>`;
  $('leave-room').onclick=()=>confirmAction('離開戰役',r.isHost?'結束後，所有同學會看到戰役結果。':'可在此分頁重新連線，繼續同一房間。',async()=>{if(r.isHost&&s.status!=='FINISHED')await rpc('hostLiveAction',live.pin,live.token,'close');stopPolling();live=null;showView('camp');});
  if(r.isHost&&s.status!=='FINISHED'){const b=document.createElement('button');b.className='btn primary';b.textContent=s.status==='WAITING'?'開始作答':s.phase==='reveal'?(s.index+1>=s.count?'完成戰役':'下一題 →'):s.phase==='answer'?'揭曉軍功 · 公佈答案':'開放作答';b.onclick=async()=>{b.disabled=true;await advanceLiveHost(r);};$('live-actions').appendChild(b);}
  $$('[data-stratagem]').forEach(b=>b.onclick=async()=>{const kind=b.dataset.stratagem;$$('[data-stratagem]').forEach(x=>x.disabled=true);try{await liveRpc_('useRaceStratagem',[live.pin,live.token,s.index,kind]);battleFlash(RACE_TOOLS[kind][0]+' · 出策！');lastLiveQuestion='';await refreshLive();}catch(e){toast(e.message);lastLiveQuestion='';await refreshLive();}});
  if(r.isHost&&s.status==='WAITING'){const share=document.createElement('button');share.className='btn';share.textContent='顯示入房 QR Code';share.onclick=()=>showSharePanel(live.pin);$('live-actions').appendChild(share);}
  if(q?.kind&&s.status==='PLAYING')mountLiveInteractive(r);
  if(s.phase==='reveal')$('competition-board').classList.add('competition-reveal');
  $$('[data-live-choice]').forEach(b=>b.onclick=async()=>{$$('[data-live-choice]').forEach(x=>x.disabled=true);try{await liveRpc_('submitLiveAnswer',[live.pin,live.token,s.index,b.dataset.liveChoice]);lastLiveQuestion='';await refreshLive();}catch(e){toast(e.message);lastLiveRender='';lastLiveQuestion='';await refreshLive();}});
  lastLiveRender=signature;lastLiveQuestion=key;
}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&live)refreshLive();});
