/* live.js — 4.0 feature module; shared app state is initialized by app.js. */
function liveHome(){stopPolling();showView('live');$('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">同步研習 · LIVE SESSION</div><h2>烽火連營，同步進軍。</h2><p>主持人控制每題的思考、作答與揭曉。學生在可使用個人裝置時加入。</p></div></div>${DEMO?'<div class="notice">本機預覽不提供真正的多人房間。部署至 Apps Script 後，以下功能會連接你的試算表。</div>':''}<div class="mode-grid"><div class="dark-card"><div class="eyebrow">軍師主持</div><h3>建立戰役</h3><p class="teacher-note">使用首頁已選的「${esc(selectedChapter())}」，最多 ${$('count').value} 題。</p><button class="btn primary full" id="host-room" style="margin-top:22px" ${DEMO?'disabled':''}>建立六位碼房間</button></div><div class="dark-card"><div class="eyebrow">諸將集結</div><h3>加入戰役</h3><label for="room-pin" class="small muted">六位房間碼</label><input id="room-pin" maxlength="6" inputmode="numeric" placeholder="輸入房間碼" style="margin-top:8px"><button class="btn primary full" id="join-room" style="margin-top:14px" ${DEMO?'disabled':''}>領軍入營</button></div></div>`;
  $('host-room').onclick=async()=>{if(!await ensureTeacher())return;const b=$('host-room');b.disabled=true;try{const r=await rpc('createLiveRoom',teacherToken,options());live={pin:r.pin,token:r.hostToken,isHost:true};storage.set('live',live);startPolling();}catch(e){toast(e.message);b.disabled=false;}};
  $('join-room').onclick=()=>{const pin=$('room-pin').value;if(!/^\d{6}$/.test(pin)){toast('請輸入六位數字房間碼。');return;}profileDialog(async p=>{try{const r=await rpc('joinLiveRoom',pin,p);live={pin,token:r.playerToken,isHost:false};storage.set('live',live);startPolling();}catch(e){toast(e.message);}});};
  const previous=storage.get('live');if(previous&&!DEMO){const b=document.createElement('button');b.className='btn';b.style.marginTop='25px';b.textContent='接續房間 '+previous.pin;b.onclick=()=>{live=previous;startPolling();};$('live-view').appendChild(b);}}
function stopPolling(){pollEpoch++;clearTimeout(poll);poll=null;pollBusy=false;}
function startPolling(){stopPolling();lastLiveRender='';lastLiveQuestion='';showView('live');$('live-view').innerHTML='<div class="empty"><i class="loading"></i>正在偵察戰況…</div>';pollLive();}
async function refreshLive(){clearTimeout(poll);if(pollBusy){if(live)live.refresh=true;return;}await pollLive();}
async function pollLive(){if(!live||pollBusy)return;if(document.hidden){poll=setTimeout(pollLive,8000);return;}const current=live,epoch=pollEpoch;pollBusy=true;let wait=4000,finished=false;try{const r=await rpc('getLiveState',current.pin,current.token);if(live!==current||epoch!==pollEpoch)return;renderLive(r);finished=r.state.status==='FINISHED';if(finished)storage.remove('live');}catch(e){if(live!==current||epoch!==pollEpoch)return;toast(e.message);lastLiveRender='';wait=8000;if(!$('live-retry')){$('live-view').innerHTML='<div class="empty">戰況暫未接通。<br><button class="btn" id="live-retry">重試連線</button> <button class="btn ghost" id="live-back">返回主營</button></div>';$('live-retry').onclick=refreshLive;$('live-back').onclick=()=>{stopPolling();live=null;showView('camp');};}}finally{if(live===current&&epoch===pollEpoch){pollBusy=false;if(!finished){const refresh=current.refresh;current.refresh=false;poll=setTimeout(pollLive,refresh?0:wait);}}}}

let lastLiveRender="",lastLiveQuestion="";
function renderLive(r){const signature=JSON.stringify(r);if(signature===lastLiveRender)return;lastLiveRender=signature;const questionKey=Competition.questionKey(r);if(lastLiveQuestion===questionKey&&document.getElementById('competition-board')){$('competition-board').innerHTML=competitionBoard(r);return;}lastLiveQuestion=questionKey;const s=r.state,q=r.question;const title=s.status==='WAITING'?'諸將集結':s.status==='FINISHED'?'本次戰役已結束':`第 ${s.index+1} 關 · ${PHASES[{think:0,discuss:1,answer:2,reveal:3}[s.phase]]}`;
  $('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">烽火連營 · 房間 ${esc(live.pin)}</div><h2>${title}</h2><p>${r.isHost?'你是主持人。':'你是參與將領。'}${s.status==='PLAYING'?(r.isHost?'請用下方軍令推進階段。':'等待主持人推進；每題只可提交一次。'):''}</p></div><button class="btn ghost small" id="leave-room">${r.isHost&&s.status!=='FINISHED'?'結束房間':'返回軍機處'}</button></div>${s.status==='WAITING'?`<div class="dark-card"><span class="eyebrow">集結令</span><div class="pin">${esc(live.pin)}</div><p class="muted">請同學在自己的裝置輸入以上房間碼。</p></div>`:''}<div id="competition-board">${competitionBoard(r)}</div>${q&&s.status==='PLAYING'?`<article class="paper"><div class="eyebrow">${esc(q.chapter)}</div><div class="sentence">${sentenceHTML(q)}</div><p class="prompt">${q.kind?esc(IQ.names[q.kind]):"「"+esc(q.targetWord)+"」的意思是甚麼？"}</p><div class="options ${s.phase==='think'?'hidden':''}">${q.options.map((o,i)=>`<button class="option ${q.correct===o?'correct':''}" data-live-choice="${esc(o)}" ${r.isHost||s.phase!=='answer'||r.submitted?'disabled':''}><span class="letter">${'ABCD'[i]}</span>${esc(o)}</button>`).join('')}</div>${q.correct?`<div class="feedback">參考釋義：${esc(answerText(q))}。${esc(q.explanation||'請說明這個解釋如何符合語境。')}</div>`:''}${r.submitted?(s.phase==='reveal'?'<p>已完成本題；比較你的判斷與解釋。</p>':'<p>軍報已交，等候揭曉。</p>'):''}</article>`:''}<div class="toolbar" id="live-actions" style="margin-top:20px"></div>`;
  $('leave-room').onclick=()=>confirmAction('鳴金收兵',r.isHost?'結束房間後，所有同學會看到戰役結束。':'離開後可從烽火連營接續房間。',async()=>{if(r.isHost&&s.status!=='FINISHED')await rpc('hostLiveAction',live.pin,live.token,'close');stopPolling();live=null;showView('camp');});
  if(r.isHost&&s.status!=='FINISHED'){const action=s.status==='WAITING'?'start':({think:'discuss',discuss:'answer',answer:'reveal',reveal:'next'}[s.phase]);const label={start:'諸將已齊 · 開始',discuss:'進入商議',answer:'開放作答',reveal:'截止作答 · 揭曉',next:s.index+1>=s.count?'完成戰役':'下一關'}[action];const b=document.createElement('button');b.className='btn primary';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await rpc('hostLiveAction',live.pin,live.token,action);await refreshLive();}catch(e){toast(e.message);b.disabled=false;}};$('live-actions').appendChild(b);}
  if(q?.kind&&s.status==='PLAYING')mountLiveInteractive(r);
  if(s.phase==='reveal')$('competition-board').classList.add('competition-reveal');
  if(r.isHost&&s.status==='WAITING'){const share=document.createElement('button');share.className='btn';share.textContent='顯示入營 QR Code';share.onclick=()=>showSharePanel(live.pin);$('live-actions').appendChild(share);}
  $$('[data-live-choice]').forEach(b=>b.onclick=async()=>{$$('[data-live-choice]').forEach(x=>x.disabled=true);try{await rpc('submitLiveAnswer',live.pin,live.token,s.index,b.dataset.liveChoice);toast('軍報已提交。');await refreshLive();}catch(e){toast(e.message);lastLiveRender='';await refreshLive();}});
}
