/* Multiplayer flow is independent from the teacher-operated four-team classroom. */
const LIVE_PHASE_NAMES={think:'準備作答',discuss:'準備作答',answer:'作答中',reveal:'答案與戰況'};
function liveHome(){stopPolling();showView('live');$('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">自主競速 · LIVE RACE</div><h2>烽火連營，競速闖關。</h2><p>每人用自己的裝置作答。先比分數，同分再比答對用時。</p></div></div>${DEMO?'<div class="notice">示範版沒有真正多人房間，請使用正式網上入口。</div>':''}<div class="mode-grid"><div class="dark-card"><h3>老師主持</h3><p>「${esc(selectedChapter())}」· 最多 ${$('count').value} 題</p><label>戰役時限<select id="race-duration"><option value="300">5 分鐘</option><option value="600" selected>10 分鐘</option><option value="900">15 分鐘</option></select></label><p>開始一次，學生即可各自連續作答。</p><button class="btn primary full" id="host-room" ${DEMO?'disabled':''}>建立六位碼房間</button></div><div class="dark-card"><h3>學生加入</h3><label for="room-pin">六位房間碼</label><input id="room-pin" maxlength="6" inputmode="numeric" placeholder="輸入房間碼"><button class="btn primary full" id="join-room" ${DEMO?'disabled':''}>加入競答</button></div></div>`;
  $('host-room').onclick=async()=>{if(!await ensureTeacher())return;const b=$('host-room');if(!b)return;b.disabled=true;try{const r=await rpc('createLiveRoom',teacherToken,{...options(),mode:'race',durationSec:Number($('race-duration').value)});live={pin:r.pin,token:r.hostToken,isHost:true};storage.set('live',live);startPolling();}catch(e){toast(e.message);b.disabled=false;}};
  $('join-room').onclick=()=>{const pin=$('room-pin').value.trim();if(!/^\d{6}$/.test(pin)){toast('請輸入六位數字房間碼。');return;}const previous=storage.get('live');if(previous?.pin===pin&&!previous.isHost){live=previous;startPolling();return;}profileDialog(async p=>{try{$('live-view').innerHTML='<div class="empty">正在加入房間…</div>';const r=await rpc('joinLiveRoom',pin,p);live={pin,token:r.playerToken,isHost:false};storage.set('live',live);startPolling();}catch(e){liveHome();$('room-pin').value=pin;toast(e.message);}});};
  const previous=storage.get('live');if(previous&&!DEMO){const b=document.createElement('button');b.className='btn';b.textContent='重新連線 · 房間 '+previous.pin;b.onclick=()=>{live=previous;startPolling();};$('live-view').appendChild(b);}}
let liveAutoTimer=null,liveAutoKey='',liveHostBusy=false;
function stopPolling(){pollEpoch++;clearTimeout(poll);clearTimeout(liveAutoTimer);liveAutoTimer=null;liveAutoKey='';poll=null;pollBusy=false;}
function startPolling(){stopPolling();lastLiveRender='';lastLiveQuestion='';showView('live');$('live-view').innerHTML='<div class="empty"><i class="loading"></i>正在接通房間…</div>';pollLive();}
async function refreshLive(){clearTimeout(poll);if(pollBusy){if(live)live.refresh=true;return;}await pollLive();}
async function pollLive(){if(!live||pollBusy)return;if(document.hidden){poll=setTimeout(pollLive,5000);return;}const current=live,epoch=pollEpoch;pollBusy=true;let wait=3000,finished=false;try{const r=await rpc('getLiveState',current.pin,current.token);if(live!==current||epoch!==pollEpoch)return;renderLive(r);finished=r.state.status==='FINISHED';if(finished)storage.remove('live');}catch(e){if(live!==current||epoch!==pollEpoch)return;toast(e.message);lastLiveRender='';lastLiveQuestion='';wait=6000;if(!$('live-retry')){$('live-view').innerHTML='<div class="empty">連線暫時中斷，房間資料仍保留。<br><button class="btn" id="live-retry">重新連線</button> <button class="btn ghost" id="live-back">返回主營</button></div>';$('live-retry').onclick=refreshLive;$('live-back').onclick=()=>{stopPolling();live=null;showView('camp');};}}finally{if(live===current&&epoch===pollEpoch){pollBusy=false;if(!finished){const refresh=current.refresh;current.refresh=false;poll=setTimeout(pollLive,refresh?0:wait);}}}}

async function advanceLiveHost(){if(liveHostBusy)return;liveHostBusy=true;try{await rpc('hostLiveAction',live.pin,live.token,'start');await refreshLive();}catch(e){toast(e.message);}finally{liveHostBusy=false;}}
function liveMini(r){const done=r.players.filter(p=>p.finished).length,me=Competition.standings(r.players).find(p=>p.isMe);return '<div class="live-mini"><strong>'+(r.state.status==='WAITING'?r.players.length+' 人已入營':done+' / '+r.players.length+' 人完成')+'</strong><span>'+(r.isHost?'學生各自連續作答':me?'你：'+me.score+' 分 · 暫列第 '+me.rank+' 位 · '+(r.myProgress||0)+' / '+r.state.count+' 題':'')+'</span>'+(r.state.status==='PLAYING'?'<span>剩餘約 '+Math.max(0,Math.ceil((r.state.endsAt-r.serverNow)/60000))+' 分鐘</span>':'')+'</div>';}
const RACE_TOOLS={hint:['孔明點撥','借東風，尋文脈','扇'],clue:['破陣辨疑','去偽存真，尋得線索','破'],rally:['背水一戰','答錯可再試一次','盾']};
function stratagems(r){return '<section class="stratagems" aria-label="三大錦囊"><div class="eyebrow">軍師授策 · 每場各一次</div><div class="stratagem-grid">'+Object.entries(RACE_TOOLS).map(([k,v])=>'<button class="stratagem '+k+'" data-stratagem="'+k+'" '+(r.tools?.[k]?'disabled':'')+'><svg viewBox="0 0 80 80" aria-hidden="true"><path d="M40 7 66 22 64 58 40 74 16 58 14 22Z"/><circle cx="40" cy="39" r="22"/><text x="40" y="48" text-anchor="middle">'+v[2]+'</text></svg><strong>'+v[0]+'</strong><small>'+(r.tools?.[k]?'本場已用':v[1])+'</small></button>').join('')+'</div>'+Object.entries(r.tools||{}).filter(([k,t])=>t.index===r.state.index).map(([k,t])=>'<div class="stratagem-note '+k+'" role="status"><b>'+RACE_TOOLS[k][0]+'</b> · '+esc(t.text)+'</div>').join('')+(r.retryPending?'<div class="stratagem-note rally" role="alert">背水一戰！剛才未答對，請再想一想。這次答對可得 1 分。</div>':'')+'</section>';}
function liveOutcome(r){if(r.isHost)return '';const o=r.lastResult,done=r.finished||r.state.status==='FINISHED',me=Competition.standings(r.players).find(p=>p.isMe);if(!o&&!done)return '';return '<div class="live-outcome '+(o?.correct?'victory':'rally')+'" role="status"><span class="live-emblem" aria-hidden="true">'+(done?'♛':o?.correct?'⚑':'策')+'</span><strong>'+(done?(r.state.status==='FINISHED'?(me?.rank===1?'本役第一 · 凱旋！':'戰役結束'):'你已完成 · 靜候諸軍歸營'):o.correct?(o.streak>=2?o.streak+' 連捷！':'答對 · 進軍！'):'整軍再戰')+'</strong>'+(o?'<p>上一題 ＋'+o.points+' 分 · 答案：'+esc(o.answer)+'</p><details><summary>查看解析</summary>'+esc(o.explanation)+'</details>':'')+(done?'<p>先比分數，同分比答對用時。全員完成或時間到後確定最終名次。</p>':'')+'</div>';}
let lastLiveRender='',lastLiveQuestion='';
function renderLive(r){
  if(r.lastResult&&live.lastFeedback!==r.lastResult.index){live.lastFeedback=r.lastResult.index;storage.set('live',live);sound(r.lastResult.correct);if(r.lastResult.correct)battleFlash(r.lastResult.streak>=2?r.lastResult.streak+' 連捷！':'答對 · 進軍！');}const signature=JSON.stringify(r);if(signature===lastLiveRender)return;
  const key=Competition.questionKey(r)+JSON.stringify([r.tools,r.retryPending,r.finished]);if(lastLiveQuestion===key&&document.getElementById('competition-board')){$('competition-board').innerHTML=competitionBoard(r);$('live-mini').innerHTML=liveMini(r);lastLiveRender=signature;return;}
  const s=r.state,q=r.question,title=s.status==='WAITING'?'已入房 · 等候老師開始':s.status==='FINISHED'?'本次戰役已結束':r.isHost?'諸軍競速 · 即時戰況':r.finished?'完成所有關卡':`第 ${s.index+1} / ${s.count} 題 · 作答中`;
  $('live-view').innerHTML=`<div class="page-head scene-head scene-live"><div><div class="eyebrow">烽火連營 · 房間 ${esc(live.pin)}</div><h2>${title}</h2><p>${r.isHost?'開始後毋須推進，以下顯示全班進度。':s.status==='WAITING'?'你已成功加入；老師開始後，題目會自動出現。':'讀題後直接作答，下一題自動出現。首次答對 3 分；同分再比用時。'}</p></div><button class="btn ghost small" id="leave-room">${r.isHost&&s.status!=='FINISHED'?'結束房間':'返回主營'}</button></div><div id="live-actions" class="toolbar live-host-controls"></div>${s.status==='WAITING'&&r.isHost?`<div class="dark-card"><span class="eyebrow">六位房間碼</span><div class="pin">${esc(live.pin)}</div><p>請學生在自己的裝置選「加入課堂」，輸入此碼。</p></div>`:''}<div id="live-mini">${liveMini(r)}</div>${liveOutcome(r)}${q&&!r.isHost?stratagems(r):''}${q&&s.status==='PLAYING'?`<article class="paper live-question"><div class="eyebrow">${esc(q.chapter)}</div><div class="sentence">${sentenceHTML(q)}</div><p class="prompt">${q.kind?esc(IQ.names[q.kind]):'「'+esc(q.targetWord)+'」的意思是甚麼？'}</p><div class="options">${q.options.map((o,i)=>`<button class="option ${q.correct===o?'correct':''}" data-live-choice="${esc(o)}" ${r.isHost||s.phase!=='answer'||r.submitted||r.tools?.clue?.index===s.index&&r.tools.clue.removedOption===o?'disabled':''}><span class="letter">${'ABCD'[i]}</span>${esc(o)}</button>`).join('')}</div>${q.correct!==undefined?`<div class="feedback">參考答案：${esc(answerText(q))}。${esc(q.explanation||'請指出原文依據。')}</div>`:''}</article>`:''}${r.review?.length?`<details class="paper"><summary>戰後復盤 · 查看每題答案與解析</summary>${r.review.map(x=>`<div class="feedback"><strong>第 ${x.index+1} 題 · ${x.correct?'答對':'待鞏固'}</strong><p>${sentenceHTML({sentence:x.prompt})}</p><p>參考答案：${esc(x.answer)}</p><p>${esc(x.explanation)}</p></div>`).join('')}</details>`:''}<details class="live-standings" open><summary>軍功榜及同學進度</summary><div id="competition-board">${competitionBoard(r)}</div></details>`;
  $('leave-room').onclick=()=>confirmAction('離開戰役',r.isHost?'結束後，所有同學會看到戰役結果。':'可在此分頁重新連線，繼續同一房間。',async()=>{if(r.isHost&&s.status!=='FINISHED')await rpc('hostLiveAction',live.pin,live.token,'close');stopPolling();live=null;showView('camp');});
  if(r.isHost&&s.status==='WAITING'){const b=document.createElement('button');b.className='btn primary';b.textContent='開始競速';b.onclick=async()=>{b.disabled=true;await advanceLiveHost();};$('live-actions').appendChild(b);}
  $$('[data-stratagem]').forEach(b=>b.onclick=async()=>{const kind=b.dataset.stratagem;$$('[data-stratagem]').forEach(x=>x.disabled=true);try{await rpc('useRaceStratagem',live.pin,live.token,s.index,kind);battleFlash(RACE_TOOLS[kind][0]+' · 出策！');lastLiveQuestion='';await refreshLive();}catch(e){toast(e.message);lastLiveQuestion='';await refreshLive();}});
  if(r.isHost&&s.status==='WAITING'){const share=document.createElement('button');share.className='btn';share.textContent='顯示入房 QR Code';share.onclick=()=>showSharePanel(live.pin);$('live-actions').appendChild(share);}
  if(q?.kind&&s.status==='PLAYING')mountLiveInteractive(r);
  if(s.phase==='reveal')$('competition-board').classList.add('competition-reveal');
  $$('[data-live-choice]').forEach(b=>b.onclick=async()=>{$$('[data-live-choice]').forEach(x=>x.disabled=true);try{await rpc('submitLiveAnswer',live.pin,live.token,s.index,b.dataset.liveChoice);lastLiveQuestion='';await refreshLive();}catch(e){toast(e.message);lastLiveRender='';lastLiveQuestion='';await refreshLive();}});
  lastLiveRender=signature;lastLiveQuestion=key;
}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&live)refreshLive();});
