/* session.js — 4.0 feature module; shared app state is initialized by app.js. */
async function startClassroom(){if(!boot?.total)return;if(!await ensureTeacher())return;showModal('頒布課堂軍令','<p>同學使用紙筆及白板。評分由老師按判斷、證據、解釋各給一分。</p><label for="lesson-class">班別</label><input id="lesson-class" name="className" value="2A" maxlength="20" required><label for="team-count">軍團數目</label><select id="team-count" name="teams"><option>4</option><option>5</option><option>6</option></select>',async f=>{const opts=options();const r=await rpc('getClassroomQuestions',teacherToken,opts);const n=Number(f.get('teams'));game=newGame('classroom',r.questions);game.className=String(f.get('className'));game.school=boot.schools[0]||'';game.teams=Array.from({length:n},(_,i)=>({name:TEAMS[i]||['麒麟軍','鳳凰軍'][i-4],score:0}));game.history=[];closeModal();begin();},'開始課堂攻城');}
function newGame(type,questions,profile={}){return {id:uid(),type,questions,guided:type!=='classroom'&&storage.get('guided',true),learning:{},index:0,phase:0,answers:[],attempts:[],hinted:false,timedOut:false,done:false,score:0,profile,seed:options().seed,chapter:$('chapter').value,date:new Date().toISOString(),awards:{}};}
async function startPractice(){if(!boot?.total)return;profileDialog(async p=>{try{setBusy(true);const opts=options();const r=await rpc('startPractice',p,opts);game=newGame('practice',r.questions,p);game.runId=r.runId;game.seed=opts.seed;begin();}catch(e){toast(e.message);}finally{setBusy(false);}});}
function setBusy(b){busy=b;$('start-classroom').disabled=$('start-practice').disabled=b||!boot?.total;}
function persist(){if(game&&!storage.set('active',game))toast('瀏覽器儲存空間不足，請在離開前匯出戰報。');}
function begin(){if(!game.questions.length){toast('沒有可用題目。');return;}stopTimer();persist();showView('battle');renderQuestion();}
function answerText(q){return q.kind?IQ.format(q):q.correct;}
function sentenceHTML(q){const t=String(q.sentence),needle=String(q.targetWord);const i=t.indexOf(needle);return i<0?esc(t):esc(t.slice(0,i))+'<mark>'+esc(needle)+'</mark>'+esc(t.slice(i+needle.length));}
function renderQuestion(){$('options').classList.remove('hidden','interactive-options','iq-revealed');stopTimer();remaining=game.type==='classroom'?30:60;updateTimer();const q=game.questions[game.index],classroom=game.type==='classroom';document.body.classList.toggle('practice-mode',!classroom);document.body.classList.toggle('review-mode',game.type==='vault');
  $('battle-type').textContent=classroom?'課堂攻城 · 教師主持':game.type==='vault'?'溫故知新 · 個人重溫':'單騎千里 · 獨立研習';$('battle-title').textContent=q.chapter;$('battle-subtitle').textContent=classroom?'每人先留下答案，再與同伴商議。':'仔細閱讀句子，按語境判斷字詞意思。';$('question-count').textContent=`第 ${game.index+1} 關 / 共 ${game.questions.length} 關`;$('progress').style.width=(game.index/game.questions.length*100)+'%';$('q-chapter').textContent='《'+q.chapter+'》';$('sentence').innerHTML=sentenceHTML(q);$('question-prompt').textContent=`句中「${q.targetWord}」的意思是甚麼？`;
  $('print-before').classList.toggle('hidden',!classroom);$('teams-card').classList.toggle('hidden',!classroom);$('practice-card').classList.toggle('hidden',classroom);$('phases').classList.toggle('hidden',!classroom);$('skip').classList.toggle('hidden',classroom||game.done);$('personal-score').textContent=game.score;
  $('hint-box').classList.add('hidden');$('feedback').classList.add('hidden');$('hint').disabled=game.done;$('advance').classList.toggle('hidden',!classroom&&!game.done);
  const choices=shuffle([q.correct,...q.distractors],game.seed+game.index);$('options').innerHTML=choices.map((v,i)=>`<button class="option ${game.attempts.includes(v)?(v===q.correct?'correct':'wrong'):''}" data-choice="${esc(v)}"><span class="letter">${'ABCD'[i]}</span><span>${esc(v)}</span></button>`).join('');
  $$('.option').forEach(b=>{b.disabled=classroom||game.done||game.attempts.includes(b.dataset.choice);b.onclick=()=>answer(b.dataset.choice);});
  if(classroom){renderPhase();renderTeams();}else{$('q-label').textContent='語境判讀';$('coach-title').textContent='看清楚，再判斷';$('coach').textContent='先找字詞前後的線索。需要協助時可使用錦囊；提示後答對也能獲得軍功。';if(game.done)revealPractice();}
  if(q.kind){$('question-prompt').textContent=IQ.names[q.kind];$('battle-subtitle').textContent='點選或拖曳完成任務，再確認答案。';renderInteractive($('options'),q,{disabled:classroom||game.done,revealed:game.done||(classroom&&game.phase===3),onSubmit:answer,seed:game.seed+game.index});}
  if(game.hinted&&!game.done)showHint(false);resetLearningPanel();
}
function renderPhase(){const phase=game.phase;$('phases').innerHTML=PHASES.map((s,i)=>`<div class="phase ${i===phase?'current':''}">${i+1}　${s}</div>`).join('');$('q-label').textContent=PHASES[phase];$('coach-title').textContent=PHASES[phase];$('coach').textContent=COACH[phase];$('options').classList.toggle('hidden',phase===0);$('advance').textContent=phase===3?(game.index===game.questions.length-1?'完成戰役 →':'下一關 →'):['進入商議 →','準備亮板 →','揭曉與修訂 →'][phase];
  if(phase===3){const q=game.questions[game.index];if(q.kind)renderInteractive($('options'),q,{disabled:true,revealed:true});$$('.option').forEach(b=>b.classList.toggle('correct',b.dataset.choice===q.correct));$('feedback').textContent=`參考釋義：${answerText(q)}。${q.explanation||'請回到句中，說明這個解釋為何符合語境；並在自己的答案補上一處理由。'}`;$('feedback').classList.remove('hidden');} }
function renderTeams(){const key=game.index;const checks=game.awards[key]||{};$('teams').innerHTML=game.teams.map((t,i)=>`<div class="team"><div class="team-name"><span class="team-identity"><i class="team-avatar" style="--commander:var(--asset${i%4})" aria-hidden="true"></i>${esc(t.name)}</span><strong>${t.score}</strong></div><div class="team-controls">${['判斷','證據','解釋'].map((s,j)=>`<button class="btn ghost" data-team="${i}" data-criterion="${j}" ${checks[i+':'+j]||game.phase!==3?'disabled':''}>${s} ＋1</button>`).join('')}</div><div class="bar"><i style="width:${Math.min(100,t.score/(game.questions.length*3)*100)}%"></i></div></div>`).join('');$$('[data-team]').forEach(b=>b.onclick=()=>award(Number(b.dataset.team),Number(b.dataset.criterion)));$('undo-score').disabled=!game.history.length;}
function award(i,j){const key=i+':'+j;game.awards[game.index]=game.awards[game.index]||{};if(game.awards[game.index][key]||game.phase!==3)return;game.awards[game.index][key]=true;game.teams[i].score++;battleFlash("穩步推進");game.history.push({index:game.index,team:i,key});persist();renderTeams();sound();}
function undoScore(){const a=game.history.pop();if(!a)return;delete game.awards[a.index][a.key];game.teams[a.team].score=Math.max(0,game.teams[a.team].score-1);persist();renderTeams();}
function advance(){if(!game||game.completed)return;if(learningRequired()&&game.done&&!Number.isInteger(learningEntry().reflection)){toast('選一句反思，再前往下一關。');return;}if(game.type==='classroom'&&game.phase<3){game.phase++;stopTimer();persist();renderPhase();renderTeams();return;}if(game.type!=='classroom'&&!game.done)return;
  if(game.index+1>=game.questions.length){finish();return;}game.index++;game.phase=0;game.attempts=[];game.hinted=false;game.timedOut=false;game.done=false;$('options').classList.remove('hidden');persist();renderQuestion();}
function answer(choice){if(!game||game.type==='classroom'||game.done||game.attempts.includes(choice))return;if(!learningReady()){toast('先選一段線索和作答把握；不肯定也可以試。');return;}const q=game.questions[game.index];if(q.kind&&game.attempts.length>=12){skipQuestion();return;}game.attempts.push(choice);
  if(choice===q.correct){stopTimer();game.done=true;const first=game.attempts.length===1&&!game.hinted&&!game.timedOut;game.score+=first?3:1;game.answers.push({id:q.id,attempts:game.attempts.slice(),hinted:game.hinted,timedOut:false,firstCorrect:first,score:first?3:1});sound();battleFlash(first?"一語中的":"溫故知新");revealPractice();}
  else{sound(false);$('feedback').textContent='先回到原文：有沒有足夠線索支持這個選項？比較一下，再試一次。';$('feedback').className='feedback error';const b=$$('.option').find(b=>b.dataset.choice===choice);if(b){b.classList.add('wrong');b.disabled=true;}if(q.kind)toast('再調整一次，然後確認答案。');}
  persist();}
function revealPractice(){const q=game.questions[game.index];if(q.kind)renderInteractive($('options'),q,{disabled:true,revealed:true});$('options').classList.remove('hidden');$$('.option').forEach(b=>{b.disabled=true;b.classList.toggle('correct',b.dataset.choice===q.correct);});$('feedback').className='feedback';$('feedback').textContent=`參考釋義：${answerText(q)}。${q.explanation||'把這個意思代回原句，再讀一次，檢查語意是否通順。'}`;$('advance').textContent=game.index===game.questions.length-1?'完成戰役 →':'下一關 →';$('advance').classList.remove('hidden');$('skip').classList.add('hidden');$('hint').disabled=true;$('personal-score').textContent=game.score;renderLearning();renderReflection();}
function skipQuestion(timeout=false){if(!game||game.done||game.type==='classroom')return;stopTimer();game.done=true;game.timedOut=timeout;game.answers.push({id:game.questions[game.index].id,attempts:game.attempts.slice(),hinted:game.hinted,timedOut:timeout,firstCorrect:false,score:0});persist();revealPractice();}
function showHint(set=true){if(!game||game.done)return;if(set){game.hinted=true;persist();}const q=game.questions[game.index];$('hint-box').textContent=q.hint||`先讀「${q.targetWord}」前後的文字，辨認誰在做甚麼；把各選項代回原句，看看哪個意思最通順。`;$('hint-box').classList.remove('hidden');}
function stopTimer(){if(timerHandle){remaining=Math.max(0,Math.ceil((timerDeadline-Date.now())/1000));clearInterval(timerHandle);timerHandle=null;}$('timer-toggle').textContent='開始計時';}
function updateTimer(){$('timer').textContent=remaining+' 秒';}
function toggleTimer(){if(!game||game.done)return;if(timerHandle){stopTimer();updateTimer();return;}if(remaining<=0)remaining=game.type==='classroom'?30:60;timerDeadline=Date.now()+remaining*1000;$('timer-toggle').textContent='暫停';timerHandle=setInterval(()=>{remaining=Math.max(0,Math.ceil((timerDeadline-Date.now())/1000));updateTimer();if(remaining===0){stopTimer();sound(false);if(game.type==='classroom')toast('思考時間到。由老師決定何時進入下一階段。');else toast('可以慢慢讀；時間到不會自動揭曉答案。');}},250);}
function addTime(){remaining+=15;if(timerHandle)timerDeadline+=15000;updateTimer();}
function profileKey(p){return [p.studentSchool,p.studentClass,p.studentNumber].join('|');}
function updateVault(){if(game.type==='classroom')return;const key=profileKey(game.profile),all=storage.get('vault',{}),items=all[key]||[];const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  game.questions.forEach((q,i)=>{const a=game.answers[i];if(!a)return;let m=items.find(x=>x.id===q.id);if(!a.firstCorrect){if(!m){m={...q,level:0,last:today,status:'ACTIVE'};items.push(m);}m.level=0;m.last=today;m.status='ACTIVE';}else if(m&&m.status==='ACTIVE'&&m.last!==today){m.level++;m.last=today;if(m.level>=3)m.status='RESOLVED';}});all[key]=items;storage.set('vault',all);}
async function finish(){stopTimer();if(!game||game.completed)return;game.completed=true;storage.remove('active');const records=storage.get('records',[]);if(!records.some(x=>x.id===game.id)){updateVault();game.accuracy=game.type==='classroom'?0:Math.round(game.answers.filter(a=>a.firstCorrect).length/game.questions.length*100);records.push({id:game.id,type:game.type,date:new Date().toISOString(),profile:game.profile,score:game.score,maxScore:game.questions.length*3,accuracy:game.accuracy});storage.set('records',records.slice(-200));}renderResult();await syncResult();}
function renderResult(){showView('result');const classroom=game.type==='classroom',wrong=game.questions.filter((q,i)=>!game.answers[i]?.firstCorrect);$('result-view').innerHTML=`<div class="victory-banner"><div class="eyebrow">捷報入營 · AFTER ACTION REPORT</div><h2>${classroom?'諸將同心，學有所進。':'每一次訂正，都是進步。'}</h2><p>${game.questions.length} 關研習已完成。帶着這次的發現，走向下一篇文章。</p><div class="victory-stamp">${classroom?'同心':'精進'}</div></div>${classroom?`<div class="stats-grid class-stats">${game.teams.map(t=>`<div class="stat">${esc(t.name)}<b>${t.score}</b><span class="muted">軍功 · 判斷／證據／解釋</span></div>`).join('')}</div>`:`<div class="stats-grid"><div class="stat">本次軍功<b>${game.score}</b><span class="muted">滿分 ${game.questions.length*3}</span></div><div class="stat">獨立首答正確<b>${game.accuracy}%</b><span class="muted">使用提示後不計入首答</span></div><div class="stat">值得重溫<b>${wrong.length}</b><span class="muted">不同日子再試一次</span></div></div>`}<div class="notice" id="sync-status">正在整理戰報…</div><div class="toolbar"><button class="btn primary" id="result-home">返回軍機處</button><button class="btn" id="export-report">匯出戰報</button>${classroom?'<button class="btn" id="print-paper">列印答題紙</button>':'<button class="btn" id="result-vault">查看錯題</button><button class="btn" id="share-seed">複製同題挑戰連結</button>'}<button class="btn hidden" id="retry-sync">重試同步</button></div>${!classroom&&wrong.length?'<div class="rule"></div><h3 class="gold">本次重溫札記</h3>'+wrong.map(q=>`<article class="mistake"><span class="eyebrow">${esc(q.chapter)}</span><p>${esc(q.sentence)}</p><span class="gold">「${esc(q.targetWord)}」：${esc(answerText(q))}</span></article>`).join(''):''}`;
  mountLearningResult();$('result-home').onclick=()=>{game=null;showView('camp');};$('export-report').onclick=exportReport;$('retry-sync').onclick=syncResult;if(classroom)$('print-paper').onclick=printPaper;else{$('result-vault').onclick=openVault;$('share-seed').onclick=shareSeed;}}
async function syncResult(){const current=game;if(!current||!$('sync-status'))return;if(current.type==='vault'){$('sync-status').textContent='重溫已保存在此瀏覽器的個人錯題紀錄。';return;}try{$('retry-sync').disabled=true;let r;if(current.type==='classroom'){if(!await ensureTeacher())throw Error('尚未登入教師帳戶。');r=await rpc('saveClassroom',teacherToken,{id:current.id,school:current.school,className:current.className,chapter:current.chapter,questions:current.questions.length,teams:current.teams});}else r=await rpc('savePractice',current.runId,current.answers);if(game!==current||!$('sync-status'))return;$('sync-status').textContent=r.local?'本機示範：戰報已保存在此瀏覽器，沒有寫入 Google Sheets。':'戰報已成功寫入 Google Sheets。';$('retry-sync').classList.add('hidden');storage.remove('pending');}catch(e){storage.set('pending',current);if($('sync-status')){$('sync-status').textContent='尚未同步：'+e.message;$('retry-sync').classList.remove('hidden');}}finally{if($('retry-sync'))$('retry-sync').disabled=false;}}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportReport(){const report={version:'4.0',learning:game.learning||{},type:game.type,date:game.date,className:game.className||game.profile.studentClass,number:game.profile.studentNumber,teams:game.teams,score:game.score,accuracy:game.accuracy,questions:game.questions.map((q,i)=>({chapter:q.chapter,sentence:q.sentence,targetWord:q.targetWord,...game.answers[i]}))};download('出師北伐-戰報.json',JSON.stringify(report,null,2));}
function printPaper(){$('print-sheet').innerHTML=`<header><h1>出師北伐 · 課堂答題紙</h1><p>班別：________　姓名／學號：________　日期：________</p><p>先獨立判斷，再找證據，討論後用另一種顏色修訂。</p></header>`+game.questions.map((q,i)=>`<article><b>第 ${i+1} 關 · ${esc(q.chapter)}</b><p>${esc(q.sentence)}</p><p>${q.kind?esc(IQ.names[q.kind])+"："+q.payload.items.map((s,i)=>(i+1)+". "+esc(s)).join(" ／ ")+(q.payload.targets?"；對應："+q.payload.targets.map(esc).join(" ／ "):""):"「"+esc(q.targetWord)+"」的意思："}________________________</p><p>我的證據與理由：</p><div class="writing-line"></div><p>討論後，我補充／修改：</p><div class="writing-line"></div></article>`).join('');window.print();}
async function shareSeed(){const base=DEMO?location.href.split('?')[0]:onlineLink(),url=new URL(base);url.searchParams.set('seed',game.seed);url.searchParams.set('chapter',game.chapter);url.searchParams.set('count',game.questions.length);try{await navigator.clipboard.writeText(url.toString());toast('已複製挑戰連結；使用同一版本題庫時題組相同。連結不包含學生姓名。');}catch(e){showModal('同題挑戰',`<p>題庫更新可能改變題組。請複製以下連結：</p><label for="share-url">挑戰網址</label><input id="share-url" readonly value="${esc(url)}">`,()=>closeModal(),'完成');}}
function openVault(){stopTimer();const p=storage.get('profile');if(!p){profileDialog(()=>openVault());return;}const items=(storage.get('vault',{})[profileKey(p)]||[]).filter(x=>x.status==='ACTIVE');showView('vault');$('vault-view').innerHTML=`<div class="page-head scene-head scene-vault"><div><div class="eyebrow">溫故而知新 · REVIEW</div><h2>重整行囊，再進一步。</h2><p>${esc(p.studentClass)} · ${esc(p.studentNumber)} 號｜在三個不同日子獨立答對，完成重溫。</p></div><button class="btn ghost" id="switch-profile">切換將領</button></div><div class="notice">錯題保存在這部裝置的瀏覽器，不會自動跨裝置同步。當日反覆練習不提升重溫等級。</div>${items.length?`<button class="btn primary" id="review-start">開始重溫 · ${Math.min(30,items.length)} 題</button>`:'<div class="empty">尚無待重溫題目。<br>先完成一次單騎研習，你的錯題便會出現在這裏。</div>'}${items.map(q=>`<article class="mistake"><div class="row between"><span class="eyebrow">${esc(q.chapter)}</span><span class="pill">重溫 ${q.level} / 3</span></div><p>${esc(q.sentence)}</p><span class="gold">考點：${esc(q.targetWord)}</span></article>`).join('')}`;$('switch-profile').onclick=()=>profileDialog(openVault);if($('review-start'))$('review-start').onclick=()=>{game=newGame('vault',items.slice(0,30),p);begin();};}
